### ISSUE TITLE
Add Grouping Support

### ISSUE THREAD

**Issue by forkineye** [forkineye/ESPixelStick#1]
Add the ability to multiply pixel inputs for "grouped" outputs.  For example, "group by 10" would generate 10 pixel outputs for every pixel input (3 channels) received via E1.31.

**Comment by madsci1016** [comment]
Have you done anything towards this yet? It's been bouncing around my head for a little while. Especially a good way to present the configuration on the web page.

**Comment by forkineye** [comment]
I hadn't yet. I was thinking of a single "Grouping" entry, with either a text box or drop down for group size (defaulted to 1).

**Comment by forkineye** [comment]
Add reversing as well

**Comment by marx1** [comment]
I have a need for this. Until it's added I still have to use a E6804 in an all pixelstick show.

**Comment by penfold42** [comment]
I’ll likely have a need for this shortly

Has anyone done anything yet ?
If not, I’ll do it

**Comment by forkineye** [comment]
I haven't started on it yet.  I'm planning to redo the ringbuffers in ESPAsyncE131 this weekend, but it shouldn't affect this.  Thanks!

**Comment by penfold42** [comment]
#147 

Done in pixeldriver for ws2811.
Should be easy to adapt for serial - I have no fixtures to test with

**Comment by forkineye** [comment]
ws2811 is fine, thanks!
