### ISSUE TITLE
Please add RDM support

### ISSUE THREAD

**Issue by elektroservis** [forkineye/ESPixelStick#104]
Hi

RDM support The addition of RDM support for DMX512 mode is great.

**Comment by MartinMueller2003** [comment]
What problem does this solve? I suspect that DMX output is a very small percentage of ESP deployments. Is this worth doing? Keep in mind that the ESP is not a lighting desk. It is an E1.31 (or similar protocols) converter.

**Comment by forkineye** [comment]
We have no plans to add RDM support at this time.  If anyone would to submit and a use case, we can look at it for ehnacement.
