### ISSUE TITLE
Reboot on AP Fallback

### ISSUE THREAD

**Issue by gjccat** [forkineye/ESPixelStick#110]
There is an issue in the wshandler.h when the index page loads the in softap mode on a ESP8266 12E

json["hostname"] = (String)WiFi.hostname();

The above line causes an error 28 reboot.

I believe that it is due to the wifi.hostname returning null as discussed in https://github.com/micropython/micropython/issues/3341

Checking for null and returning an empty hostname string stops the reboot.

**Comment by penfold42** [comment]
Is this still an issue in the latest build ?

I know I squashed a similar bug if the config.json was corrupt

**Comment by gjccat** [comment]
Yes,

The fix i put in my code is

            String s = WiFi.hostname();
            if (s != NULL) { 
              json["hostname"] = (String) WiFi.hostname();
            }
            else
            {
              json["hostname"] = (String)"";
            }

at line 164 in procG in wshandler.h

the issue is that the WiFi hostname returns null and you cant covert null to a string

**Comment by penfold42** [comment]
What are the steps to reproduce this? It appears to work fine for me

I just built from source, (commit b4e08e8c8ca5937d8e8b3ac6fa0727fe43b2ebc0)
ardunio 1.8.5 on linux
esp8266 core from github (commit 8ae0746e4aeaf7c2a8881831f370b40347e47a50)

I changed ap_fallback to true in the config and then uploaded sketch and spiffs

**Comment by gjccat** [comment]
in a Wemos D1 or NodeMCU when it falls back to ap mode as no access point is available and you connect and browse to 192.168.4.1 the module resets.  I did a debug trace and that was the line it was failing on.

**Comment by gjccat** [comment]
Just rebuild with
Arduino 1.8.7 on Windows and ESP 2.4.2 Release. Still the same issue.

.....................
*** Failed to connect ***
*** Timeout - Reverting to default SSID ***

Connecting to ENTER_SSID_HERE as esps-7440ca
Connecting with DHCP..............................
*** Failed to connect ***
*** FAILED TO ASSOCIATE WITH AP, GOING SOFTAP ***
- Web Server started on port 80
- Unicast port: 5568
- Listening for 510 channels, from Universe 1 to 1
* WS Connect - 1

Exception (28):
epc1=0x40224340 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3fffeb50 end: 3fffffb0 offset: 01a0

>>>stack>>>

**Comment by penfold42** [comment]
I just cannot get it to fail...

I've tried 2.4.2 release with lwip2:
ESPixelStick v3.1-dev (Nov  5 2018)
SDK:2.2.1(cfd48f3)/Core:2.4.2/lwIP:2.0.3(STABLE-2_0_3_RELEASE/glue:arduino-2.4.1-13-g163bb82)/BearSSL:6d1cefc

I've tried 2.4.2 with lwip1.4:
SDK:2.2.1(cfd48f3)/Core:2.4.2/lwIP:1.4.0rc2/BearSSL:6d1cefc

**Comment by gjccat** [comment]
Sorry to be a pain with this one. Spent some time on this last night. Did a full install of Arduino IDE on a new PC, Got the latest code and built no crash. so sat down and di a comparison of the environments.

The key was ArduinoJSON 5.6.7  when setting a null to the JSON it causes a reboot.   This has been fixed from 5.7.1 on.

As far as I am concered this issue is closed.

**Comment by penfold42** [comment]
excellent - thanks for tracking it down
