### ISSUE TITLE
Sequence Error tracking in Serial mode

### ISSUE THREAD

**Issue by madsci1016** [forkineye/ESPixelStick#12]
One thing I wasn't able to get back and solve before the merge is tracking packet errors in serial mode.  The code will crash if error tracking statements are uncommitted. I'm sure it's a simple mistake on my part but I have not been able to fix it yet. Its stable now, but does not do sequence error tracking in serial mode.

**Comment by forkineye** [comment]
It's working for me using Serial1 and DMX.  Can you verify this is still an issue with the current master?
