### ISSUE TITLE
ESP8266 Alternative 5.8ghz

### ISSUE THREAD

**Issue by jeylites** [forkineye/ESPixelStick#127]
Hi I reached out to  FNLink that makes similar WiFi models to the ESP8266, running on 5.8Ghz. They have given me a selection but I’m not sure which is best for this project. I
 was wondering if someone could alter the code to run on these modules. The reason I’m asking for a 5.8G solution from a 2.4G device is i’m having frequent WiFi disconnection in the area I’m at.

I will be more than happy to forward the information I received from the company. 

http://www.fn-link.com/

http://www.ofeixin.com/

**Comment by forkineye** [comment]
The code for this project is tied very closely to the ESP8266 platform due to the way the pixel stream is generated.  Sorry, not going to happen.
