### ISSUE TITLE
Add persistent effects for devices with limited WiFi connectivity

### ISSUE THREAD

**Issue by forkineye** [forkineye/ESPixelStick#128]
This will consist of an auto-start option for effects in the test / effects tab along with a save button.  When checked and saved, the effect should persist and auto-start upon reboot regardless if a WiFi association is made. If enabled, the ESP8266 will not reboot if association reaches the timeout period.  Effect state should be saved in config.json.  This will override E1.31 just as if it were enabled via the web page or via MQTT.

**Comment by extremeskillz** [comment]
Looks like a good option to me. Would be nice to have a prop in its own mode when not connected to FPP or Xlights for like a demo or independent effects to display.

**Comment by penfold42** [comment]
I need this too for one of my use cases.
Home automation where I need the lights to default to “on x%” on a power cycle.

Ideally on ASAP before even trying to associate

**Comment by LightUpMA** [comment]
I was going to request this feature; great minds think alike!!

**Comment by penfold42** [comment]
@forkineye have you started this yet ?

If not I’ll make a start on it by doing the webUI and config parsing

**Comment by penfold42** [comment]
All done in #136 except for the wifi startup changes.

**Comment by penfold42** [comment]
What’s missing from ESPixelStick ?

Is it just more effects you want ?

**Comment by mattncsu** [comment]
Nothing is missing, it does exactly what it says it should do. I just like the idea of some built in patterns so simple effects can be run without the need for FPP or xLights running on another machine. It would make it more one-size fits all if it supported streaming from a show source _and_ some built in effects.

**Comment by penfold42** [comment]
Cool - there’s 8 effects there today.

Adding more is pretty easy.
First one that comes to mind is a 2 colour transition - a start colour and an end colour and have it smooth fade from one to the other

**Comment by gjccat** [comment]
Can we have a save button to persist th the selected "effect" as opposed to having to change the default effect in the source.

**Comment by penfold42** [comment]
Yes, that’s what my pull request #136 does

![b94fbe7e-e719-403d-9483-2360322699b4](https://user-images.githubusercontent.com/13173376/48246398-65672380-e443-11e8-8042-a323424c2bc4.png)

**Comment by penfold42** [comment]
#136 is merged
 Close ?

**Comment by forkineye** [comment]
Thanks @penfold42
