### ISSUE TITLE
Add DMX 512 Support

### ISSUE THREAD

**Issue by Blickensderfer** [forkineye/ESPixelStick#14]
Having DMX output option would be awesome.

**Comment by forkineye** [comment]
It's in there, but I haven't been able to test it yet - https://github.com/forkineye/ESPixelStick/commit/15ffe33d532523bfd99688914f3359fa7afc0c6e

**Comment by Blickensderfer** [comment]
I would like to test it if you need testers.

**Comment by forkineye** [comment]
Verified DMX is working.  You'll need to either use a solution that provides RS485 output, or add a RS485 transceiver to the ESPixelStick hardware.

**Comment by Blickensderfer** [comment]
I would use the Data and connect it to the Data In on the RS485 circuit something like this?
![send_sn75276a](https://cloud.githubusercontent.com/assets/20225988/16717508/d642fd30-46e4-11e6-8d77-ed9a79aba695.jpg)

**Comment by forkineye** [comment]
@Blickensderfer That should work.  You can go that route, or just pull the rs485 chip in your existing controller and feed the data line straight into the host processor, similar to how Bill does with his - http://www.billporter.info/2015/09/05/renardesp-wifi-adapter-for-renard-dimmers.  The data line and ground should be all you need.

**Comment by petiepooo** [comment]
Closed issue, I know, but I'm wondering if a RS422 transceiver like the 8-lead no-enables chip shown at https://www.intersil.com/content/dam/Intersil/whitepapers/interface/rs-485-transceiver-tutorial.pdf would work.  That would avoid the need for the passive on the RO pin.
