### ISSUE TITLE
How can I switch off the startup led?

### ISSUE THREAD

**Issue by NightD3v** [forkineye/ESPixelStick#144]
How can I turn off the startup light or that only one led lights up. Dimmed would also be a possibility.

**Comment by forkineye** [comment]
This is dependent upon your board.  On an ESP-01, the red and blue LEDs are hardwired to power and serial data.

**Comment by NightD3v** [comment]
Not the LED from the board... when i turn on the board all the ws2812 leds light up but i want to have these off

**Comment by bquesse** [comment]
Some 'WS281x' leds that you find online are not true WS281x and include a compatible clone of the chip. This clone chip, whatever it is, has the quirk of turning all the lights on by default when they receive power but no data - usually they are blue, but this could vary. This could be what you are dealing with.
