### ISSUE TITLE
IOT Security

### ISSUE THREAD

**Issue by Lutzion** [forkineye/ESPixelStick#152]
As in the actual version there is no default PSK (and changeable) on the one hand 
and it is possible to do an over the air firmware update on the other hand  
this is an security risk.

In my environment i start my router and the PixelStick (same plug) at the same time.
Router needs more time to boot and thus the PixelStick ends up in open SoftAP mode forever.
Now everybody can connect without a password and 
- see my wlans credentials and
- install his own firmware.

So it would be better to set a default password

Sample
=====================================================================
            char chipId[9] = { 0 };
            snprintf(chipId, sizeof(chipId), "%08X", ESP.getChipId());

            WiFi.mode(WIFI_AP);
            String ssid = "ESPixelStick_" + String(chipId) ;
            Serial.println(String("**** FAILED TO ASSOCIATE WITH AP, GOING SOFTAP **** " + ssid));

            // reverse chipId
            String strPsk = String(chipId) ;
            reverse(strPsk.begin(),strPsk.end());
            sprintf(chipId, strPsk.c_str()) ;

            WiFi.softAP(ssid.c_str(), chipId); // password needs at least 8 chars
======================================================================
In this case psk for the device ESPixelStick_12345678 would be 87654321.

Next way to improve security is to let the PixelStick reboot or restart the wifi in SoftAP mode if there is no connection after a configured timeout (for example 2 minutes).
In this case - if router will be bootet in the meantime - the PixelStick will connect to the router and everything is save.

sample
=====================================================================
#define STA_ACN_TIMEOUT 120000  /* 120 seconds */
uint32_t        lastFullUniverseTime = 0 ;  // set the time to this variable only after e131 data received
...

in loop()
...
    uint32_t iTimeout = STA_ACN_TIMEOUT;
    
    switch(WiFi.getMode())
    {
    case(WiFiMode::WIFI_AP):        // AP without client
    case(WiFiMode::WIFI_AP_STA):    // AP with client (browser connected to 192.168.4.1)
        iTimeout = STA_ACN_TIMEOUT ;
        break ;
    default:
        iTimeout = CONNECT_TIMEOUT ;
        break ;
    }

    if ((millis() - lastFullUniverseTime) > iTimeout)
    {
        Serial.print(String("Mode ") + String(WiFi.getMode())) ;
        Serial.println(String(" -> TIMEOUT ") + String(iTimeout)) ;
        initWifi() ;
        lastFullUniverseTime = millis() ; // new interval for waiting
    }
...

I hope this explains why and how to increase security.

**Comment by penfold42** [comment]
Configurable Client mode timeout done in #153

**Comment by penfold42** [comment]
@Lutzion can this be closed now that 153 is merged ?

**Comment by Lutzion** [comment]
I havent checked so far, but at least it will be more safe than before.
I still would advice to implement a configurable PSK, but close it, if you want.

**Comment by forkineye** [comment]
AP mode should really not be enabled in a live environment.  Its purpose is to provide a flashed module to someone when you don't know their credentials so that they may flash it or to act as a safety / fallback when changing your wifi credentials.  Highly recommend you disable it once your stick is configured.
