### ISSUE TITLE
Problems getting ESPSFlashTool to run

### ISSUE THREAD

**Issue by sydkahn** [forkineye/ESPixelStick#158]
In all the tutorials I can find, they say double click on the jar file.  When I do that I get two error dialogs from java. Firmware not found and unable to load configuration file.

This happens on my both my desktop and laptop. Both win10, on the laptop installed the latest java.  

I just downloaded from github as a zip - unzipped and tried to run the jar from the dist folder. In a window -  also tried from the command line.

Then I tried to load in arduino IDE - installed all of the libraries - when trying to compile that - get a slew of errors - The last on is something about max not defined 

Totally stuck - any help?

**Comment by forkineye** [comment]
Are you unzipping them to a folder or trying to run it from within the zip file?

**Comment by sydkahn** [comment]
unzipping to folder off the download directory

**Comment by forkineye** [comment]
Which release of ESPixelStick are you downloading? Can you paste the link?  I just tested the latest Travis-CI build against Java 1.8.0_201 on Windows 10 and it runs just fine.

**Comment by forkineye** [comment]
Oh, sounds like you're downloading the source code release. You want the main zip in the release, not the source one. The files in dist are used to build the binary release package.

**Comment by sydkahn** [comment]
https://github.com/forkineye/ESPixelStick.git  clicked zip https://github.com/forkineye/ESPixelStick.git
Just downloaded a fresh copy - same results

The zip I get is named ESPixelStick-master.zip

**Comment by forkineye** [comment]
That's the source code. If you want a binary release, you download those from the release tab - https://github.com/forkineye/ESPixelStick/releases. The latest "Stable" release is 3.0 - 
https://github.com/forkineye/ESPixelStick/releases/latest

**Comment by sydkahn** [comment]
AHHHHH - I am so used to pulling source from GIT - Thanks for your help - am running down to shop to do some flashing 

Small Question - will there even be a version for the ESP32 - that is what I am playing around with lately - got lots of them

**Comment by forkineye** [comment]
Nothing planned for ESP32 right now, Thanks!
