### ISSUE TITLE
Multiple Universes on one stick?

### ISSUE THREAD

**Issue by fizgig10** [forkineye/ESPixelStick#161]
I'm seeing hints of this in the forum here but no actual documentation that I can nail down.  I'm guessing that the ESpixel value "Universe" might better be called the "Starting Universe Number" where if you set the it to 1, "Universe Boundary" to 510 and "Pixel Count" to something more than 170, it automatically rolls to universe 2?  EX:  Pixel #172 would be addressed as universe 2, channel 2?  That sound right?

**Comment by forkineye** [comment]
Close. Pixel #171 would be at universe 2, channel 1 and #172 would start at channel 4 (3 channels per pixel).  The tooltip for the field has been updated to better reflect this - https://github.com/forkineye/ESPixelStick/blob/master/html/index.html#L139.
"DMX Universe to listen for. Consecutive DMX Universes will be monitored as needed."
