### ISSUE TITLE
MQTT Reconnect

### ISSUE THREAD

**Issue by Xstasy** [forkineye/ESPixelStick#163]
When the MQTT server restarts the ESPixelStick doesn't seem to reconnect, is there any reconnect functionality coded in?

**Comment by penfold42** [comment]
`void onMqttDisconnect(AsyncMqttClientDisconnectReason reason) {
    LOG_PORT.println(F("- MQTT Disconnected"));
    if (WiFi.isConnected()) {
        mqttTicker.once(2, connectToMqtt);
    }
}`
