### ISSUE TITLE
Support for mDNS?  Access it as "pixelstick01.local" instead of "192.168.x.x"

### ISSUE THREAD

**Issue by jakabo27** [forkineye/ESPixelStick#168]
It would be nice if it could support mDNS so that we could assign a multicast DNS name so that within our network we can type itsName.local to access it instead of the IP address.

**Comment by NorthernMan54** [comment]
By default it does this, try _hostname_.local

And if you use a mdns browser like discovery you should see them listed under

_ddp._udp and _e131._udp
