### ISSUE TITLE
Effects T6-T8 missing 

### ISSUE THREAD

**Issue by sascha777** [forkineye/ESPixelStick#172]
Hi guys,
just got my ESPixelStick up and running (3.1-dev), which is really cool! Thanks for that!
I am just wondering why some effects aren't available. I saw that a fire effect should be available and can find it in the sources as well. But on the website is see only effects T0-T5. T6-T8 aren't available. Haven't tried to adress them by MQTT yet.
Any clues why they are missing on the website?

**Comment by sascha777** [comment]
Tried now with v3.0 release, pre-release 20190319150609 as well with master gulped and uploaded with arduino ide.
Still can't find T6-T8 :-(

**Comment by sascha777** [comment]
Tried also to find on testing page without success

**Comment by penfold42** [comment]
You uploaded both the code and the spiffs parts ?

**Comment by sascha777** [comment]
Yes, I did. Website looks normal, only the effect dropdown shows only 5 instead of 8 effects.

**Comment by sascha777** [comment]
Found it! The effect were find until prerelease 20190116222043.
Since 20190319150422 three effects are missing.
Can't check in the code as the releases are untagged.

**Comment by phazed0** [comment]
Thank you for the great work on this project!

I can confirm and have the exact problem as @sascha777. 

Further, the Chase (T5) is visible in my list but does not work (no lights on).

**Comment by LarryDysart** [comment]
I found on wshandler.h:line 196, if I increase DynamicJsonDocument json(2048); it works again

**Comment by forkineye** [comment]
Been fixed for a while, think back in 3.1.
