### ISSUE TITLE
Combine with normal push switch

### ISSUE THREAD

**Issue by xciser77** [forkineye/ESPixelStick#175]
I would like to make a custom ceiling light on my sons bedroom with led strips. For the funfactor I would like to add a ESPixelStick to let it make special fx.

The problem I am facing is I need to add a normal (zwave/wifi) switch for normal use. Does anyone has a solution to add this ?

**Comment by phazed0** [comment]
You would need to run it through something like Home Assistant (local) or other IFTTT service. Then you could really "tie the room together".

**Comment by forkineye** [comment]
Set the default via effects and flag it to save state. You start up with that effect when turned on. Or d as phazed0 suggested.
