### ISSUE TITLE
ESPSFlashTool dont work on my pc

### ISSUE THREAD

**Issue by maik-dmxc** [forkineye/ESPixelStick#177]
hi,

just downloaded and unziped ESPixelStick_Firmware-3.0
ESPSFlashTool.jar bring up an error

`Unable to find firmware configuration file`

`maik@maik-XMG-A505:~$ java -jar '/home/maik/Desktop/ESPixelStick_Firmware-3.0/ESPSFlashTool.jar' 
OS: linux / amd64
`
same with sudo
`maik@maik-XMG-A505:~$ sudo java -jar '/home/maik/Desktop/ESPixelStick_Firmware-3.0/ESPSFlashTool.jar' 
OS: linux / amd64
`

regards maik

**Comment by mvinaround** [comment]
Also not working... Missing the .bin files?

**Comment by tpmodding** [comment]
same problem...just startet the tool a few times suddenly it worked...

**Comment by forkineye** [comment]
@maik-dmxc Run java from the same directory in which you extracted the zip file or it won't be able to find the binaries in the subdirectories. The paths referenced from within the jar file and relative and will be broken if you try to run it from another location.

**Comment by leivos** [comment]
I also get "Unable to find firmware configuration file". I tried to run ESPSFlashTool.jar form the directory where ESPixelStick-master is located. I tried it also inside ESPixelStick-master directory and within dist directory.

Could some of the files be missing from the zip? I can't find spiffs/config.json, for example.

**Comment by leivos** [comment]
I tried an older version (ESPixelStick_Firmware-3.0rc3). There I was able to start ESPSFalshTool.jar. and load the program but Serial Output didn't return any IP address.

Oh, and I noticed that the latest version has config.json but it's inside data/. Still can't get that new version working.

**Comment by forkineye** [comment]
Unable to reproduce any issues with this.

**Comment by tapi35** [comment]
Hello Leivos, do you have resolve the problem ? I'm in the same situation. I don't understand. I can flash the 3.0 version but after flashing, there's no wifi connection, ESPFlashtool don't do nothing. And when I want to use the master version, I have many errors like you. If you have resolve the problem, I'm interrested. Thanks
