### ISSUE TITLE
where can i get the hardware?

### ISSUE THREAD

**Issue by monoboy4** [forkineye/ESPixelStick#180]
Hello im inquiring where i can get the hardware?  if its no longer in production can i get files to order and build my own hardware?

**Comment by cccale1** [comment]
here is an option: https://jboards.ecwid.com/ESPixNode-p127558674

**Comment by CalcProgrammer1** [comment]
I just use prototyping perfboard, the kind where each hole has its own pad.  I just build up a simple circuit with a 3.3V regulator and an 8-pin header for the ESP-01, then solder on power input and pixel output wires.  It lacks the fuse and some of the nice extras of the real ESPixelStick board but it's dirt cheap and it works fine for my needs.

**Comment by forkineye** [comment]
The hardware is currently going through a redesign and should be available early next year.
