### ISSUE TITLE
Question/Feature Suggestion

### ISSUE THREAD

**Issue by drasch** [forkineye/ESPixelStick#184]
I'm extending the ESPixelstick firmware to support a dumb RGB strip. 

My question is: would this be accepted as an upstream patch. If so, where would you prefer this level of abstraction? Is it as a third option vs WS2811/GE Color, or something else?

Thanks,
David

**Comment by penfold42** [comment]
It was added by me previously in #86 and subsequently removed ...

**Comment by forkineye** [comment]
I would hold off right now. I'm going to unify the firmware for all output modes and try to make it more modular so that things like this can be added more cleanly. The code is some serious need of refactoring.

**Comment by drasch** [comment]
Thanks everyone, I will look into all the prior art.
