### ISSUE TITLE
STM 4CH relay

### ISSUE THREAD

**Issue by JuleMandenDK** [forkineye/ESPixelStick#187]
Can somebody tell me if it possible to control a 4ch relay?

Right now i have set the stick to Renard, and i can see the "output" in the diagnostic in the web interface, that i have set through the xLights software over the E3.31. But i will like this to some relays

I have found this code that is working with the 4ch relay:

Relay ( https://www.banggood.com/DC12V-ESP8266-Four-Channel-Wifi-Relay-IOT-Smart-Home-Phone-APP-Remote-Control-Switch-p-1317255.html?rmmds=myorder&cur_warehouse=CN )

`#define CH_PD 44 //sinal de controle de CH_PD
#define RST 46 //sinal de controle de RST
#define GPIO0 48 //sinal de controle de GPIO0
uint8_t R3On[] = {0xA0, 0x01, 0x01, 0xA2};
uint8_t R3Off[] = {0xA0, 0x01, 0x00, 0xA1};
uint8_t R4On[] = {0xA0, 0x02, 0x01, 0xA3};
uint8_t R4Off[] = {0xA0, 0x02, 0x00, 0xA2};
uint8_t R1On[] = {0xA0, 0x03, 0x01, 0xA4};
uint8_t R1Off[] = {0xA0, 0x03, 0x00, 0xA3};
uint8_t R2On[] = {0xA0, 0x04, 0x01, 0xA5};
uint8_t R2Off[] = {0xA0, 0x04, 0x00, 0xA4};
void setup() {
pinMode(CH_PD,OUTPUT);
pinMode(RST,OUTPUT);
pinMode(GPIO0,OUTPUT);
digitalWrite(CH_PD,HIGH); //Setado em alto - funcionamento normal
digitalWrite(RST,HIGH); //RST em alto - funcionamento normal
digitalWrite(GPIO0,HIGH); //GPIO0 em alto - funcionamento no rmal
// Inicializa ambas as portas

Serial.begin(115200);

}

void loop() {

Serial.write(R1On, 4);
delay(1000);
Serial.write(R1Off, 4);
delay(1000);
Serial.write(R2On, 4);
delay(1000);
Serial.write(R2Off, 4);
delay(1000);
Serial.write(R3On, 4);
delay(1000);
Serial.write(R3Off, 4);
delay(1000);
Serial.write(R4On, 4);
delay(1000);
Serial.write(R4Off, 4);
delay(1000);
}`

**Comment by forkineye** [comment]
Your best two options for this are to either use the ESPAsyncE131 libary directly and create a custom sketch for it, or to wait until I wrap up the unify branch which makes adding things like this much easier.
