### ISSUE TITLE
Failed to Program ESP8266

### ISSUE THREAD

**Issue by bretterer** [forkineye/ESPixelStick#194]
I have a NodeMCU that i am trying to flash ESPixelStick onto.  I am getting an error through the jar file.

I have (i think) put it in programming mode, by holding "flash" pressing and releasing"reset" and then releasing "flash"

I am connected to USB on my laptop.

<img width="502" alt="Screen Shot 2019-12-26 at 10 04 41 PM" src="https://user-images.githubusercontent.com/1906920/71499229-949a4900-282d-11ea-8224-9e9f1cbb8122.png">

I have tried running the commands directly in the terminal as well with no luck

Running version https://github.com/forkineye/ESPixelStick/releases/tag/untagged-0fbde6ad29fba5b3567b

**Comment by forkineye** [comment]
Are you on a Mac? Make sure you have write access to the serial device.  Also, grab the v3.1 release, it will auto-reset your NodeMCU into programming mode.

**Comment by bretterer** [comment]
Looks like I have the same issue with the new version.  

I am pretty sure I have write access for the serial device as well.

<img width="1243" alt="Screen Shot 2020-01-14 at 2 38 15 PM" src="https://user-images.githubusercontent.com/1906920/72376245-a3ad4200-36db-11ea-9bdc-c2e7fdd25101.png">

**Comment by forkineye** [comment]
ls -l on the serial device to verify. Also, I recall another user saying you had to be a member of the wheel group I believe to write to the serial ports on mac's.

**Comment by extremeskillz** [comment]
Same issue on Linux systems.

**Comment by extremeskillz** [comment]
What I found was the V2 hardware required the external programing UART usb hub to connect up the hardware to configure. This was reconized by the system and you were able to configure. With the latest hardware using the ESP8266 (V3 ESPixelStick and Jboards ESPixNode) the built in usb on the ESP8266 isn't being seen on the Linux and Mac systems. This is the issue currently. Windows seems to be working fine.

**Comment by forkineye** [comment]
Closed per #182
