### ISSUE TITLE
Problem Changing from esps_mode_PIXEL to esps_mode_SERIAL

### ISSUE THREAD

**Issue by clapsac** [forkineye/ESPixelStick#195]
Device mode is now a compile time option to set your device type and is configured in the top of the main sketch file. Current options are ESPS_MODE_PIXEL and ESPS_MODE_SERIAL. The default is ESPS_MODE_PIXEL for the ESPixelStick hardware.

I have 10 Wemos d1 minis flashed with 3.1 dev  working flawlessly. Programmed with Arduino IDE.  I could not get the java flash tool to work for the life of me.  

I have an older DMX flood i want to control as well.  What am i missing to change the output of the esp8226 from pixels to serial?

**Comment by forkineye** [comment]
You need to change it <mode.h>.  Try the 3.1 release that I dropped yesterday, it will throw the Wemos into programming mode automatically.
