### ISSUE TITLE
Setting up multiple universes

### ISSUE THREAD

**Issue by radioredman** [forkineye/ESPixelStick#204]
I am wondering how to set up multiple universes... Do I set the number of universes with the web interface under "Universe"?
![Capture](https://user-images.githubusercontent.com/62391523/77082498-885bfd00-69d2-11ea-8fab-4b9dec5f1828.PNG)

**Comment by forkineye** [comment]
It will listen for consecutive universes starting at "Universe" based upon your universe boundary.  In your screen shot for example, you have 600 pixels (1800 channels).  The first 510 channels (170 pixels) would be on Universe 4, the next 510 on 5, then 6, and the rest on 7.

**Comment by radioredman** [comment]
Thank you! I appreciate your response and the amazing work on this! This
clears up my confusion!
