### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by tapi35** [forkineye/ESPixelStick#206]
Hello everybody,

I want to install espixelstick on my d1 mini boards. I have tested it with the last "ESPixelStick-master" via espsflashtool. I have excatly the same problem of that : https://github.com/forkineye/ESPixelStick/issues/177
I have installed java in the same folder, nothing change
I have tested it with "ESPixelStick_Firmware-3.0". The firmware is flashing but there's no connection test after the 100% complete.
Then, I have tested via Arduino IDE, install the libraries. When I compile it, it says me 👍 
exit status 1
ESPAsyncZCPP.h: No such file or directory
I don't know what to do. Is someone would be nice to send a bin of the last version ?
I want to use for musical show, I have test  https://github.com/mtongnz/ESP8266_ArtNetNode_v2
and I don't resolve the problem that just one universe is working. I'm tired not understanding what's wrong with me.  Thanks for your help

**Comment by forkineye** [comment]
If you want trouble-free binary releases, get the from the latest release tag - https://github.com/forkineye/ESPixelStick/releases/latest
