### ISSUE TITLE
Start Channel Config

### ISSUE THREAD

**Issue by tinseltunes** [forkineye/ESPixelStick#207]
I not as issue as such, just some advice.
Should the Start channel always start at 1 or the actual start channel i.e. 225 if the model start channel is 225 in this case.

And should the universe boundary be 510 or the actual number of channels based on the pixel count i.e 64 pixels = 192 channels = Universe boundary.

Or will Xlights upload the configuration automatically when saving. I'm using the DDP protocol.

Thanks
in advance.

**Comment by mkozik13** [comment]
Cannot comment on the DDP as I still have not traveled down that path, however, mine are all set to the correct start channel shown in xLights along with the universe and I set my boundries to 510.  Hope it helps!

**Comment by forkineye** [comment]
Sorry I missed this.  The start channel is the offset into the universe you want to start listening at for that controller, and the universe boundary should match whatever you're using in your sequencer. 512 is recommended and you want to pack each universe full of data.
