### ISSUE TITLE
Add ArtNET support

### ISSUE THREAD

**Issue by refinedcranberry** [forkineye/ESPixelStick#21]
It would be nice to have ArtNET support. I already have code that acts as ArtNET node and outputs to serial if that helps.

**Comment by Jearde** [comment]
I totally agree! I also use a build with ArtNet support and an OLED for knowing, whats configured. These two things are very important for me to have an easy to use setup. I already have a Fork on the old version with OLED and ArtNet support, but I do not have the time to update it to the master branch. If you are interested, the code is in here:
https://github.com/Jearde/ESPixelStick

**Comment by MartinMueller2003** [comment]
Why would we go to an older protocol? We have E1.31 and now DDP. Does ArtNet solve any problem that cant be solved using one of the supported protocols?

**Comment by forkineye** [comment]
It still seems to be popular in certain areas and countries. I think mostly due to the newer protocols not being supported by the software they're using. I have a library I was writing for it somewhere, I'll dig around my archives.

**Comment by MartinMueller2003** [comment]
If you get me the lib, I will integrate it.

**Comment by jnovack** [comment]
https://github.com/hideakitai/ArtNet

**Comment by forkineye** [comment]
In main and staged for 4.0 release.
