### ISSUE TITLE
Summation of sequence errors in wshandler.h is incorrect

### ISSUE THREAD

**Issue by bwmcin** [forkineye/ESPixelStick#210]
On line 93 of wshandler.h the computation for sequence errors is  seqErrors =+seqError[i];  the = and + s/b reversed (right now seqErrors is just being assigned the last value in the loop.)  The corrected line s/b

seqErrors += seqError[i];

**Comment by MartinMueller2003** [comment]
This section has been completly refactored in the unify branch.

**Comment by forkineye** [comment]
Should be fixed in 4.x
