### ISSUE TITLE
Parallel output , direct port access

### ISSUE THREAD

**Issue by Kamal-Sonani** [forkineye/ESPixelStick#212]
Instead of using one single line of output , is their any changes  to take 4 parallel output (using direct port access).it Will take same time as single pin output.

On each port 500 led (512 ideally) x 4 port = 2048 led

By doing that, frame rate will be increased instead of driving  >600 led on single line.

**Comment by MartinMueller2003** [comment]
I have been looking into this and it can be done since the I2S interface can support better than 10Mb transfer rates (we need 3Mb/output port). This would also require additional external HW (beyond a level shifter). It is up to Shelby to cecide if we want to support this feature.

**Comment by forkineye** [comment]
It's currently outside the scope of ESPixelStick as it would require specific external hardware to be supported that's apart from the ESPixelStick hardware.
