### ISSUE TITLE
espixelstick in/out

### ISSUE THREAD

**Issue by tapi35** [forkineye/ESPixelStick#216]
Hello everybody !
first, thanks for this project, it work like a charm with my lights and qlc !
Now, I search to use it for another application. 
Is it possible to use one transmitter (connected to a hardware dmx controler : stairville led foot 8 dmx ) and multiple receivers (lights on the same universe) ?
Is there anybody who's try this sort of config ?
Thanks

**Comment by forkineye** [comment]
Sorry, this won't be supported as RS485 is TX only on the V3, so it can't receive DMX.
