### ISSUE TITLE
Brief flash when turned on

### ISSUE THREAD

**Issue by tinseltunes** [forkineye/ESPixelStick#217]
I've uploaded the espixel stick software onto some D1minis. When I turn then on the lights will briefly flash. Do I need to also use a resister or something to stop this from happening?

**Comment by Kamal-Sonani** [comment]
On board led ?
If yes ,you cant stop it 


Because its driven by low side, & when you start wemos, that pin will blink every time

**Comment by tinseltunes** [comment]
No, the led lights attached to it.

**Comment by Kamal-Sonani** [comment]
Post some of images or video link to verify
