### ISSUE TITLE
esp avec rasberry et fpp falcomplay

### ISSUE THREAD

**Issue by lassauce** [forkineye/ESPixelStick#226]
la fonctionne proxy pour les esp ne fonctionne pas je m'explique quand je suis sur mon Raspberry pi avec le ffp jai une option proxy qui me permet de rentre dans mes esp ou autre sans changer de réseaux mai quand je suis sur mon Raspberry et je mai adresse ip de esp en mode proxy jai aucune connections pouvez vous voir pk merci

**Comment by forkineye** [comment]
J'utilise Google Traduction. Quelqu'un peut-il mieux traduire cela pour moi?
I'm using Google Translate. Can anyone translate this better for me?

the proxy works for the esp does not work I explain myself when I am on my Raspberry pi with the ffp I have a proxy option which allows me to enter my esp or other without changing networks May when I am on my Raspberry and I may ip address of esp in proxy mode i have no connections can see you pk thanks

**Comment by patdelaney** [comment]
I think i understand the report, but before I try to explain it, I'll see
if I can reproduce it

**Comment by lassauce** [comment]
je ne peut pas aller dans les esp par le proxy de fpp

**Comment by lassauce** [comment]
WebSocket connection lost, attempting to reconnect... voila ce qui s'affiche quand je veut fair un proxy

**Comment by XBouBou** [comment]
He doesn't reach correctly ESPixelStick through the Proxy of FPP (Falcon Player ).

On the browser a message "WebSocket connection lost, attempting to reconnect..." appear from the ESPixelStick

**Comment by MartinMueller2003** [comment]
This sounds like an issue in setting up the IP address domain in the FPP.

**Comment by patdelaney** [comment]
Martin, I think I know what he is reporting, I just have not had a chance
to reproduce.

**Comment by patdelaney** [comment]
so that I can explain the scenario

**Comment by lassauce** [comment]
moi jai le souci avec tt mai esp
