### ISSUE TITLE
Add Save As button to bottom of ESPFlashtool to the serial output section section

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#235]
**Is your feature request related to a problem? Please describe.**
Add the ability to save the serial output to a file file

**Describe the solution you'd like**
Add the ability to save the serial output to a file file so that we can send the logs to developers

**Additional context**

**Comment by MartinMueller2003** [comment]
Added a button that saves both the System and Serial logs at the same time and in the same file.

**Comment by MartinMueller2003** [comment]
This is working in the latest version. A user has generated a log and attached it to another issue.
