### ISSUE TITLE
Add timestamp option to Serial section of ESPFlashtool

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#238]
**Is your feature request related to a problem? Please describe.**
Add timestamp option to Serial section of ESPFlashtool

**Describe the solution you'd like**
Add timestamp option to Serial section of ESPFlashtool similar to what is in Arduino IDE. This will help with debugging / testing.

**Additional context**

**Comment by MartinMueller2003** [comment]
Timestamps are clearly visible in a log attached by a user.
