### ISSUE TITLE
xLights upload to set outputs seems to corrupt Device Setup UI

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#255]
**ESPixelStick Firmware Version**
Latest code from Github (self compiled)
**Hardware Version**
ESP Artstick with SD card

**Binary release or compiled yourself?**
compiled

**Describe the bug**
After uploading the outputs from xLights 
go to Device setup tab and review the configuration  - it looks correct
Go to Second input mode to select Effects
Go to Effects Configuration and the effect dropdown is empty.
![image](https://user-images.githubusercontent.com/8147459/102016543-22b15d00-3d27-11eb-8cec-a0a5d7885615.png)

Rebooting the pixelstick doesn't fix the issue.

**Comment by patdelaney** [comment]
![Uploading image.png…]()

**Comment by patdelaney** [comment]
After another attempt at uploading from xLights the Relay option populated, but I can't disable it.
![image](https://user-images.githubusercontent.com/8147459/102017652-d4ec2300-3d2d-11eb-841e-595656f06d80.png)

**Comment by MartinMueller2003** [comment]
Took a look at this. xLights is sending a config file directly to the ESP using the same web socket commands as the UI. The UI is always in sync with the config on the device since they are released together. The config file being sent by xLights is WAY out of date. I would like to propose that the UI and xLights use different commands to send config data. The ESP will post process and merge the config files from xLights rather than just accept them as it does from the UI. We can do this without making any changes to xLights. I will work on this ASAP.

**Comment by MartinMueller2003** [comment]
Update: Once I deleted the controllers in xLights, xLights did a refresh and started sending an updated config. This resolved most of the issues. However, xLights sends invalid values (zero) for group size and zigzag count. Internal code corrects this but did not save the updates in the config files. This means the bad values showed up on the UI. Changes are now on the unify branch to update the config with the corrected values. We could ask the xLights team to always read the config before they send a new set of config changes (aka NEVER cache the config). This would solve the alignment issues when we make updates.

**Comment by patdelaney** [comment]
I don;t believe we do that for any other controller. I believe it's a blind
push. But checking with Dan

**Comment by MartinMueller2003** [comment]
I can see the read and the write. We just need to make sure xLights always does the read, not only when the controller is first added.
    On Monday, December 14, 2020, 03:26:45 PM EST, patdelaney <notifications@github.com> wrote:  
 
 

I don;t believe we do that for any other controller. I believe it's a blind
push. But checking with Dan

**Comment by patdelaney** [comment]
So are you saying when we add a controller in xlights at some point it
queries the controller for the output settings?

**Comment by MartinMueller2003** [comment]
Thats what it looks like.
    On Monday, December 14, 2020, 03:43:29 PM EST, patdelaney <notifications@github.com> wrote:  
 
 

So are you saying when we add a controller in xlights at some point it
queries the controller for the output settings?

**Comment by MartinMueller2003** [comment]
Now that I found and fixed a race condition in the transfer sequences, I retested this again and do not see anything bad happening. I suspect fixing the race condition also fixed this issue since the race condition resulted in corrupted configs as well.

**Comment by patdelaney** [comment]
This was fixed in xLights, it was a problem with the WebSocket library.
tested in xlights 2021.11 and 
EsPixelstick
Build Date
Apr 5 2021 - 11:58:32
