### ISSUE TITLE
Unify Branch:  Hostname of ESP32 dev board not displayed in Home tab, it shows espressif

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#256]
**ESPixelStick Firmware Version**
Unify branch latest build

**Hardware Version**
ESP32 Dev Board
**Binary release or compiled yourself?**
Compiled myself

**Describe the bug**
In Wifi Setup I set a hostname.
Reboot ESP32
Check Home page is shows wrong Hostname
It shows espressif instead of esp32-1

![image](https://user-images.githubusercontent.com/8147459/102021023-8bf29980-3d42-11eb-9d80-7820544ddd50.png)

![image](https://user-images.githubusercontent.com/8147459/102021025-90b74d80-3d42-11eb-8abf-e05fbfeb89bf.png)

**Comment by MartinMueller2003** [comment]
This is a bug in the ESP32 WiFi core code. 
Added a workaround to force the local DNS cache to become invalidated and thus updates the host name.

**Comment by patdelaney** [comment]
This has been fixed and tested
![image](https://user-images.githubusercontent.com/8147459/107290026-81473e80-6a2b-11eb-92e8-a0c75bf7099f.png)
