### ISSUE TITLE
WS2815-2818

### ISSUE THREAD

**Issue by Anlighting** [forkineye/ESPixelStick#260]
I am currently using a pixel stick with 2812b.  I would like to know who has tested with 2815-2818? I planed rebuild my project on 12v LED.

**Comment by MartinMueller2003** [comment]
The data protocol used by the WS2811 through WS2816 series pixels is identical.
Martin
    On Thursday, December 17, 2020, 09:45:30 AM EST, Anlighting <notifications@github.com> wrote:  
 
 


I am currently using a pixel stick with 2812b. I would like to know who has tested with 2815-2818? I planed rebuild my project on 12v LED.
