### ISSUE TITLE
Device Setup Page Fails To Save With Long MQTT Password

### ISSUE THREAD

**Issue by codahq** [forkineye/ESPixelStick#261]
**ESPixelStick Firmware Version**
3.1, 3.2 (maybe others)

**Hardware Version**
V2 (and JBoards V1)

**Binary release or compiled yourself?**
Binary Release

**Operating System**
Any

**Access Point**
Any

**Describe the bug**
Any

If you enable MQTT and enter in a long password (like the default password created by Home Assistant for example which is 64 characters long) the message is sent to the device over the WS but no response is received.  No error message is returned.  It just fails to save.  Decreasing the length will restore saving and functionality on the page.

**Comment by forkineye** [comment]
I'm unable to re-produce this on 3.2. Tried it with 64 and 70 character passwords. Can you get some output from the serial terminal while attempting to set it?

![image](https://user-images.githubusercontent.com/4047923/102785808-8ca3b500-436c-11eb-8ecb-8d87bde4f863.png)

**Comment by codahq** [comment]
*** procS(): Parse Error ***
S2device

**Comment by codahq** [comment]
In case this helps.

![image](https://user-images.githubusercontent.com/6679555/102854495-e1ccde80-43df-11eb-8b62-fccd84a82510.png)

**Comment by codahq** [comment]
JSON:
S2 {
  "device": { "id": "esps11" },
  "mqtt": {
    "enabled": true,
    "ip": "10.10.10.232",
    "port": "1883",
    "user": "homeassistant",
    "password": "[snipped]",
    "topic": "diy/esps/5ee333",
    "haprefix": "homeassistant",
    "clean": false,
    "hadisco": true
  },
  "e131": {
    "universe": 16,
    "universe_limit": 510,
    "channel_start": 1,
    "channel_count": 600,
    "multicast": false
  },
  "pixel": {
    "type": 0,
    "color": 0,
    "groupSize": 1,
    "zigSize": 0,
    "gammaVal": 2.2,
    "briteVal": 1
  },
  "serial": {
    "type": null,
    "baudrate": null
  }
}

**Comment by codahq** [comment]
Sample password:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
