### ISSUE TITLE
IP Fields do not properly validate contents.

### ISSUE THREAD

**Issue by MartinMueller2003** [forkineye/ESPixelStick#263]
**ESPixelStick Firmware Version**
unify - Fetched 2020.12.23

**Hardware Version**
N/A

**Binary release or compiled yourself?**
Self Built

**Operating System**
Win 10

**Access Point**
NA

**Describe the bug**
Brought up the newly modified UI. Much cleaner. One minor problem. If you delete the value in the IP fields, the validation becomes green. It should be red on an empty field.

![image](https://user-images.githubusercontent.com/8608503/103001101-55fba500-44fa-11eb-95dd-dce9e7a8dcee.png)

**Comment by forkineye** [comment]
Should be fixed with https://github.com/forkineye/ESPixelStick/commit/9131893ce9c0f19999dbf00a6bd439fafa98be07.  If / when we decide to enable / disable the save button based upon input validation, we'll need to assign valid default values for the static IP fields.

**Comment by jnovack** [comment]
Tasmota sticks with 192.168.4.1.

**Comment by MartinMueller2003** [comment]
Setting a default is not a problem. Allowing a blank field is an issue.
Martin
    On Friday, December 25, 2020, 05:39:07 AM EST, Justin J. Novack <notifications@github.com> wrote:  
 
 


Tasmota sticks with 192.168.4.1.

**Comment by patdelaney** [comment]
The first time you open the UI after compiling and uploading, and go to the wifi settings, the DHCP is not selected even though that is how it booted and got connected. 
![image](https://user-images.githubusercontent.com/8147459/103156988-396aa180-4774-11eb-9b86-fc1aab0d35aa.png)

**Comment by MartinMueller2003** [comment]
actually it used dhcp because no address was defined. look at the log. it tells you you have a config error. have not rememberd to fix the dhcp default setting.
martin

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 26, 2020 at 13:17, patdelaney<notifications@github.com> wrote:   


The first time you open the UI after compiling and uploading, and go to the wifi settings, the DHCP is not selected even though that is how it booted and got connected.

**Comment by patdelaney** [comment]
closed bogus entries in IP turn it red as expected
