### ISSUE TITLE
Configuration for FPP remote show effects as Secondary Input mode  Should it?

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#265]
**ESPixelStick Firmware Version**
Latest Check-in 12/26/2020
git rev-parse origin/unify
c0712ca83b26fa76dada34739f0bf3b9188f3865

**Hardware Version**
ESP8266

**Binary release or compiled yourself?**
self compiled

**Describe the bug**
When trying to configure the Pixel Stick as a FPP remote the Secondary input defaults to effects (see screenshot)
Should it?
![image](https://user-images.githubusercontent.com/8147459/103157547-6ec5be00-4779-11eb-8911-1cf26b8528cb.png)

**Comment by MartinMueller2003** [comment]
Not on mine:




    On Saturday, December 26, 2020, 01:57:39 PM EST, patdelaney <notifications@github.com> wrote:  
 
 


ESPixelStick Firmware Version
Latest Check-in 12/26/2020
git rev-parse origin/unify
c0712ca

Hardware Version
ESP8266

Binary release or compiled yourself?
self compiled

Describe the bug
When trying to configure the Pixel Stick as a FPP remote the Secondary input defaults to effects (see screenshot)
Should it?

**Comment by forkineye** [comment]
Web frontend is still under re-work, lots to be done but I've been away for the past week.

**Comment by patdelaney** [comment]
This no longer happens. This could have been a browser cache issue or I didn't run gulp
