### ISSUE TITLE
Multiple FPP "Upload Output" appears to corrupt Pixelstick Config and break webserver

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#266]
**ESPixelStick Firmware Version**
ESPixelStick_TRAVIS-20201224134950.zip

**Hardware Version**
esp8266

**Binary release or compiled yourself?**
ESPixelStick_TRAVIS-20201224134950.zip

**Describe the bug**
I'm trying to test workflows with xLights and there appears to be a bug with uploading the output configuration from xLights. If I do it more than once it appears to corrupt the config and basically I have to re flash the pixelstick.  I can't reliably connect to the web interface.

in xlights configure a pixelstick as a device.
Create a test sequence
upload Inputs and upload outputs to pixel stick.

It appears that the color order is saved during the upload outputs, so I try to output again, but then that fails.

Since it's my understanding that xlights polls the pixelstick to build the config that we are going to send back, there must be some bad data in the config and when xlights trys to parse it and repackages it, something in the new packet is bad, and breaks the config.

**Comment by patdelaney** [comment]
`@ about 14:12  I uploaded inputs
@ about 14:13  I uploaded Outputs
I checked Web Ui to verify content
@ about 14:14  I uploaded Outputs a 2nd time 
I check Web Ui and I got site can't re reached. It is pingable but the sebser appears to be down.
Here are the logs 



ESPixelStick v4.0-dev (NOT STABLE)(Dec 24 2020 - 13:51:01)
ESP Version: SDK:2.2.2-dev(38a443e)/Core:2.7.4=20704000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
File system initialized.
Listing directory: /
'config.json': 	'285'
Listing directory: www
'alexa.html.gz': 	'134'
'ddp.html.gz': 	'130'
'disabled.html.gz': 	'130'
'dmx.html.gz': 	'374'
'e1_31.html.gz': 	'393'
'effects.html.gz': 	'579'
'esps.css.gz': 	'13698'
'esps.js.gz': 	'57745'
'fpp_remote.html.gz': 	'391'
'gece.html.gz': 	'425'
'index.html.gz': 	'2649'
'mqtt.html.gz': 	'714'
'relay.html.gz': 	'483'
'renard.html.gz': 	'439'
'serial.html.gz': 	'544'
'ws2811.html.gz': 	'1405'
Configuration file: '/config.json' loaded.
** OutputDisabled Initialization for Chan: 0 **
** OutputDisabled Initialization for Chan: 1 **
Configuration file: '/output_config.json' not found.
EEEE Error loading Output Manager Config File. EEEE
--- WARNING: Creating a new Output Manager configuration Data set - Start ---
** WS281x Initialization for Chan: 0 **
************** Cannot Start WS2811 for channel '1'. **************
** OutputDisabled Initialization for Chan: 1 **
** GECE Initialization for Chan: 0 **
************** Cannot Start GECE for channel '1'. **************
** OutputDisabled Initialization for Chan: 1 **
** DMX Initialization for Chan: 0 **
************** Cannot Start DMX for channel '1'. **************
** OutputDisabled Initialization for Chan: 1 **
** Renard Initialization for Chan: 0 **
************** Cannot Start Renard for channel '1'. **************
** OutputDisabled Initialization for Chan: 1 **
** Serial Initialization for Chan: 0 **
************** Cannot Start Generic Serial for channel '1'. **************
** OutputDisabled Initialization for Chan: 1 **
************** Cannot Start RELAY for channel '0'. **************
** OutputDisabled Initialization for Chan: 0 **
** Relay Initialization for Chan: 1 **
** OutputDisabled Initialization for Chan: 1 **
Configuration file: '/output_config.json' saved.
**** Saved Output Manager Config File. ****
--- WARNING: Creating a new Output Manager configuration Data set - Done ---

WiFi Entering State: Connecting Using Config Credentials

WiFi Connecting to paddycakes as artstick-sd2
** 'Disabled' Initialization for input: '0' **
** 'Disabled' Initialization for input: '1' **
.Configuration file: '/input_config.json' not found.
EEEE Error loading Input Manager Config File. EEEE
--- WARNING: Creating a new Input Manager configuration Data set - Start ---
** 'E1.31' Initialization for input: '0' **
** 'Disabled' Initialization for input: '1' **
** 'E1.31' Shut Down for input: '0' Requires a reboot. **
** 'Disabled' Initialization for input: '0' **
** 'Effect Engine' Initialization for input: '1' **
** 'Disabled' Initialization for input: '0' **
** 'MQTT' Initialization for input: '1' **
** 'Effect Engine' Initialization for input: '0' **
** 'Disabled' Initialization for input: '0' **
** 'Alexa' Initialization for input: '1' **
** 'Effect Engine' Initialization for input: '0' **
** 'DDP' Initialization for input: '0' **
DDP subscribed to UDP: 
** 'Disabled' Initialization for input: '1' **
** 'FPP Remote' Initialization for Input: '0' **
** 'Disabled' Initialization for input: '1' **
** 'Disabled' Initialization for input: '0' **
Configuration file: '/input_config.json' saved.
**** Saved Input Manager Config File. ****
--- WARNING: Creating a new Input Manager configuration Data set - Done ---
- Web Server started on port 80
FPPDiscovery subscribed to broadcast
FPPDiscovery FAILED to subscribed to multicast messages
Configuration file: '/config.json' saved.
Internal Reboot Requested. Rebooting Now

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

ESPixelStick v4.0-dev (NOT STABLE)(Dec 24 2020 - 13:51:01)
ESP Version: SDK:2.2.2-dev(38a443e)/Core:2.7.4=20704000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
File system initialized.
Listing directory: /
'config.json': 	'268'
'input_config.json': 	'1284'
'output_config.json': 	'1253'
Listing directory: www
'alexa.html.gz': 	'134'
'ddp.html.gz': 	'130'
'disabled.html.gz': 	'130'
'dmx.html.gz': 	'374'
'e1_31.html.gz': 	'393'
'effects.html.gz': 	'579'
'esps.css.gz': 	'13698'
'esps.js.gz': 	'57745'
'fpp_remote.html.gz': 	'391'
'gece.html.gz': 	'425'
'index.html.gz': 	'2649'
'mqtt.html.gz': 	'714'
'relay.html.gz': 	'483'
'renard.html.gz': 	'439'
'serial.html.gz': 	'544'
'ws2811.html.gz': 	'1405'
Configuration file: '/config.json' loaded.
** OutputDisabled Initialization for Chan: 0 **
** OutputDisabled Initialization for Chan: 1 **
Configuration file: '/output_config.json' loaded.

WiFi Entering State: Connecting Using Config Credentials

WiFi Connecting to paddycakes as artstick-sd2
** 'Disabled' Initialization for input: '0' **
** 'Disabled' Initialization for input: '1' **
Configuration file: '/input_config.json' loaded.
- Web Server started on port 80
FPPDiscovery subscribed to broadcast
FPPDiscovery subscribed to multicast: 239.70.80.80
SD Card Size: 15185MB (128kB used)
System Volume Information - 0

WiFi Entering State: Connected To AP
WiFi Connected with DHCP
WiFi Connected with IP: 192.168.1.161
* WS Connect - 1
File: '/output_config.json' loaded.
File: '/input_config.json' loaded.
File: '/output_config.json' loaded.
File: '/input_config.json' loaded.
* WS Connect - 2
File: '/input_config.json' loaded.
** 'E1.31' Initialization for input: '0' **
E1.31 Multicast Enabled.
E1.31 Unicast Enabled on port: 5568
Listening for 0 channels from Universe 1 to 0.
* WS Disconnect - 2
Configuration file: '/input_config.json' saved.
**** Saved Input Manager Config File. ****
* WS Connect - 3
File: '/output_config.json' loaded.
** WS281x Initialization for Chan: 0 **
*** Requested group size count was too low. Setting to 1 ***
** 'E1.31' Initialization for input: '0' **
E1.31 Multicast Enabled.
E1.31 Unicast Enabled on port: 5568
Listening for 768 channels from Universe 1 to 2.
Configuration file: '/output_config.json' saved.
**** Saved Output Manager Config File. ****
* WS Disconnect - 3
* WS Disconnect - 1
* WS Connect - 4
File: '/output_config.json' loaded.
File: '/input_config.json' loaded.
* WS Connect - 5
File: '/output_config.json' loaded.
*** Requested group size count was too low. Setting to 1 ***
** 'E1.31' Initialization for input: '0' **
E1.31 Multicast Enabled.
E1.31 Unicast Enabled on port: 5568
Listening for 768 channels from Universe 1 to 2.
* WS Disconnect - 5
Configuration file: '/output_config.json' saved.
**** Saved Output Manager Config File. ****
* WS Disconnect - 4
* WS Connect - 6
File: '/output_config.json' loaded.
File: '/input_config.json' loaded.
* WS Disconnect - 6
* WS Connect - 7
File: '/output_config.json' loaded.
File: '/input_config.json' loaded.
* WS Connect - 8

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (9):
epc1=0x402445ae epc2=0x00000000 epc3=0x00000000 excvaddr=0x93131f7d depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffece0 end: 3fffffb0 offset: 0190
3fffee70:  3ffef5e0 0a2d9987 60000600 00000030  
3fffee80:  3fff5004 3fff1c38 3fff1c39 40242958  
3fffee90:  0000111c 3fff4ff0 00000020 40100d80  
3fffeea0:  00001b48 00000369 00000369 40100ac3  
3fffeeb0:  00000000 00000000 00000020 3fff4fec  
3fffeec0:  00000008 3fff1a48 3fff4fec 402400ed  
3fffeed0:  00000000 00000000 4bc6a7f0 00000000  
3fffeee0:  40240608 00029b08 3fff1a54 402404d0  
3fffeef0:  00000000 00000000 3fff23dc 40240610  
3fffef00:  0a2d9987 3ffef5e0 3ffef5b8 40240710  
3fffef10:  40261b0c 3ffef5b8 3ffef5e0 60000600  
3fffef20:  0a2d9987 3ffef5e0 3ffef5b8 40261b19  
3fffef30:  40261b5e 3fffdab0 00000000 3fffdcb0  
3fffef40:  3ffef5f8 3fffdab0 00000000 4026175f  
3fffef50:  40000f49 40000f49 3fffdab0 40000f49  
3fffef60:  40000e19 00000005 0007bf78 00000000  
3fffef70:  60000600 aa55aa55 0000005d 40104cf9  
3fffef80:  40104cff 0007bf78 00000000 ffffffff  
3fffef90:  4010000d ffffffff ffffffff ffffffff  
3fffefa0:  00000000 3fffef3c 00000000 3ffffcd8  
3fffefb0:  3fffffc0 00000000 00000000 feefeffe  
3fffefc0:  feefeffe feefeffe feefeffe feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  00000000 00000000 0000001f 40100494  
3ffff950:  00000005 00000000 3fffc228 40105495  
3ffff960:  4000050c 00000000 00000020 40100494  
3ffff970:  4025a378 00000030 0000001c ffffffff  
3ffff980:  40105ffb 00000000 3feffe00 00000100  
3ffff990:  00eaa101 60000200 00020000 0000407c  
3ffff9a0:  0000ffff 00042035 00002035 00000040  
3ffff9b0:  3fff24c4 00200500 00000040 00000030  
3ffff9c0:  00000000 4000444e 00000002 00040000  
3ffff9d0:  00000000 4000422e 60000200 3fff2504  
3ffff9e0:  00000100 40004aa0 000000c0 00200440  
3ffff9f0:  00000005 00000000 00000020 40100494  
3ffffa00:  00000000 4000444e 00000005 40101948  
3ffffa10:  00000000 400041bc 60000200 3fff2504  
3ffffa20:  00000100 40004b14 00000040 002004c0  
3ffffa30:  00000100 3fff24c4 3fffc718 00200500  
3ffffa40:  00000040 00000000 4010600c 00000040  
3ffffa50:  3fff24c4 00200500 00000040 00200500  
3ffffa60:  3fffc718 3fff24c4 4010600c 00000040  
3ffffa70:  002004c0 4022b87c 002004c0 3fff24c4  
3ffffa80:  3fffc718 3fff24c4 00000040 09c2289d  
3ffffa90:  00200480 4022b87c 00200480 002004c0  
3ffffaa0:  00200500 00200500 00000040 4022f221  
3ffffab0:  4022f278 00000030 00000013 00200480  
3ffffac0:  002004c0 002004c0 00000040 4022f221  
3ffffad0:  00000000 400041bc 60000200 3fff403c  
3ffffae0:  00000100 40004b14 00000040 0035a4c0  
3ffffaf0:  00000100 3fff3ffc 3fffc718 0035a500  
3ffffb00:  00000040 00000000 4010600c 00000040  
3ffffb10:  3fff3ffc 0035a500 00000040 0035a500  
3ffffb20:  3fffc718 3fff3ffc 00000080 0035a480  
3ffffb30:  0035a4c0 4022b87c 0035a4c0 3fff3ffc  
3ffffb40:  00000040 00e8a101 4010600c 00000040  
3ffffb50:  3fff3ffc 0035a4c0 00000040 0035a4c0  
3ffffb60:  0035a500 0035a500 00000040 4022f221  
3ffffb70:  0035a480 4022b87c 0035a480 3fff3ffc  
3ffffb80:  00002200 40102a4f 00000040 4022e41a  
3ffffb90:  40102bb8 00080000 00000000 0035a480  
3ffffba0:  0035a4c0 0035a4c0 00000040 4022f221  
3ffffbb0:  401028a0 2c9f0300 00000005 40101948  
3ffffbc0:  3ffea2d5 40104bf3 3ffedd60 ffffffff  
3ffffbd0:  401024df 3ffedd60 00000008 ffffffff  
3ffffbe0:  00007fff 09c2446c 3ffee730 401026bc  
3ffffbf0:  3ffeab80 00000000 00000000 3ffffd30  
3ffffc00:  00007fff 09c2446c 40102b7e 00000100  
3ffffc10:  3ffeab80 7fffffff 00002200 00000001  
3ffffc20:  00000001 00004288 00000040 00200440  
3ffffc30:  3ffeab80 3fff247c 00000040 09c2446c  
3ffffc40:  3ffeab74 2c9f0300 4000050c 3fffc278  
3ffffc50:  00000000 400042db 00000022 40101948  
3ffffc60:  40004b31 3fff247c 00000040 002004c0  
3ffffc70:  40106054 400042db 00002000 4000050c  
3ffffc80:  40000f83 00000030 0000001f fffffffe  
3ffffc90:  40000ea3 00000023 00000001 80000000  
3ffffca0:  3fffdab0 00000000 3fffdbc0 3ffea310  
3ffffcb0:  00000005 00000000 00000001 4000050c  
3ffffcc0:  40000f83 00000030 0000001f 4000050c  
3ffffcd0:  4010193e 00000030 0000001f fffffffe  
3ffffce0:  3ffea0e0 00000020 3fff18fe 3fff18fe  
3ffffcf0:  3ffee450 00000000 3fffdbc0 3ffea3f8  
3ffffd00:  00000004 3fffc6fc 00000001 00000002  
3ffffd10:  3ffee420 00000001 00000000 00000030  
3ffffd20:  00000000 00000000 0000001f 40100494  
3ffffd30:  401024e1 00000030 3fffc228 40105495  
3ffffd40:  4000050c 00000000 0000001f 40100494  
3ffffd50:  4010038e 00000030 0000001a ffffffc0  
3ffffd60:  00000005 00000000 00000020 40100494  
3ffffd70:  60000f00 00000000 00000005 40101948  
3ffffd80:  00000005 00000000 00000020 40100494  
3ffffd90:  00000002 00000000 00000005 40101948  
3ffffda0:  3ffea2d5 40104bf3 3ffedd10 40101948  
3ffffdb0:  401024df 3ffedd10 00000020 40100494  
3ffffdc0:  00000005 00000000 00000020 40100494  
3ffffdd0:  3ffeab74 00000000 00000005 40101948  
3ffffde0:  3ffea2d5 40104bf3 3ffedd10 00000100  
3ffffdf0:  401024df 3ffedd10 00002200 00000001  
3ffffe00:  00007fff 0a2d7917 3ffee730 401026bc  
3ffffe10:  3ffeab8c 00000000 00000000 0a2d3e0b  
3ffffe20:  00007fff 0a2d7917 40102b7e 00000100  
3ffffe30:  3ffeab8c 7fffffff 00002200 00000001  
3ffffe40:  00000001 00000080 00000018 ffffffff  
3ffffe50:  3ffeab8c 60000f0c 00000002 4000050c  
3ffffe60:  4000bd9c 00000030 00000010 ffffffff  
3ffffe70:  40000fb0 00000020 00000501 3fffc200  
3ffffe80:  00000521 ffffffff 00000020 fffffffe  
3ffffe90:  00000000 3fffc6fc 00000000 3fff2a34  
3ffffea0:  00000000 3fff0a00 3fff17e0 00000030  
3ffffeb0:  ffffffff 3fffc6fc 00000001 3fff18d0  
3ffffec0:  3fff17c0 3fffdad0 3fff1910 00000030  
3ffffed0:  00000000 00000000 00000000 fffffffe  
3ffffee0:  ffffffff 3fffc6fc 00000001 3ffe85a8  
3ffffef0:  00000000 3fffdad0 3fff1910 00000030  
3fffff00:  00000000 3fffdad0 3fff1910 00000030  
3fffff10:  40233130 00000000 000003e8 3fff1910  
3fffff20:  4022be3c 3fff17e0 3ffe8bc0 4022be48  
3fffff30:  00000000 4bc6a7f0 00029b03 3fff1910  
3fffff40:  00000000 00000000 4bc6a7f0 402154bd  
3fffff50:  3fff6558 402194a4 40100582 dced9168  
3fffff60:  00f42400 6635248f 3fff0c00 3fff1910  
3fffff70:  00000000 3fff17c0 3fff18d0 4022be69  
3fffff80:  00000000 00000000 00000001 40100494  
3fffff90:  3fffdad0 00000000 3fff18d0 401004b5  
3fffffa0:  3fffdad0 00000000 3fff18d0 4022e505  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

ESPixelStick v4.0-dev (NOT STABLE)(Dec 24 2020 - 13:51:01)
ESP Version: SDK:2.2.2-dev(38a443e)/Core:2.7.4=20704000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
File system initialized.
Listing directory: /
'config.json': 	'268'
'input_config.json': 	'1284'
'output_config.json': 	'1255'
Listing directory: www
'alexa.html.gz': 	'134'
'ddp.html.gz': 	'130'
'disabled.html.gz': 	'130'
'dmx.html.gz': 	'374'
'e1_31.html.gz': 	'393'
'effects.html.gz': 	'579'
'esps.css.gz': 	'13698'
'esps.js.gz': 	'57745'
'fpp_remote.html.gz': 	'391'
'gece.html.gz': 	'425'
'index.html.gz': 	'2649'
'mqtt.html.gz': 	'714'
'relay.html.gz': 	'483'
'renard.html.gz': 	'439'
'serial.html.gz': 	'544'
'ws2811.html.gz': 	'1405'
Configuration file: '/config.json' loaded.
** OutputDisabled Initialization for Chan: 0 **
** OutputDisabled Initialization for Chan: 1 **
** WS281x Initialization for Chan: 0 **
Configuration file: '/output_config.json' loaded.

WiFi Entering State: Connecting Using Config Credentials

WiFi Connecting to paddycakes as artstick-sd2
** 'Disabled' Initialization for input: '0' **
** 'Disabled' Initialization for input: '1' **
.** 'E1.31' Initialization for input: '0' **
Configuration file: '/input_config.json' loaded.
- Web Server started on port 80
FPPDiscovery subscribed to broadcast
FPPDiscovery FAILED to subscribed to multicast messages

WiFi Entering State: Connected To AP
WiFi Connected with DHCP
WiFi Connected with IP: 192.168.1.161
E1.31 Multicast Enabled.
E1.31 Unicast Enabled on port: 5568
Listening for 768 channels from Universe 1 to 2.`

**Comment by patdelaney** [comment]
[xlights.log](https://github.com/forkineye/ESPixelStick/files/5743597/xlights.log)
attaching xlights log

**Comment by forkineye** [comment]
Does this go with https://github.com/forkineye/ESPixelStick/issues/255?

**Comment by patdelaney** [comment]
They may be related in the end, but with this issue the pixelstick webserver just stops working.  I can ping it but that is it.

**Comment by MartinMueller2003** [comment]
This tells me there is something odd going on in the Ethernet layer: "FPPDiscovery FAILED to subscribed to multicast messages". That should never fail since the WiFi and Ethernet objects are established long before the setup call is made. That means the WiFi config got corrupted. I can tell you that based on the logs, the App configs are ok. It also looks like you have the Web UI connected to the ESP at the same time as the XLights sockets are open. That uses a lot of memory and causes reboots on the device.  The ESP does not work well with multiple concurrent web sockets open. File transfers will fail badly in such a mode.

**Comment by patdelaney** [comment]
tested with Build Date
Apr 5 2021 - 11:58:32   and upload input adn upload output work as expected.
Tested ESP32 and ESP8266
tested against xLights 2021.11
