### ISSUE TITLE
Please add New Section to Home screen called FPP Remote and then display the sync packet count

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#267]
**Is your feature request related to a problem? Please describe.**
Not really related to a problem , but more for Troubleshooting

**Describe the solution you'd like**
As a user I would like too see the number of sync packets that Pixelstick is getting just like E1.31 data

**Additional context**
![image](https://user-images.githubusercontent.com/8147459/103158976-7beaa900-4789-11eb-8676-cccdc0743737.png)

**Comment by MartinMueller2003** [comment]
I am not sure what additional information you are looking for. DDP does not have the concept of universes, nor does the user have a choice about how the data is wrapped. DDP sends blocks of contiguous channels and adjusts the block size based on the ack rate (if the sender implements adaptive rate control.
Martin  
    On Saturday, December 26, 2020, 03:49:14 PM EST, patdelaney <notifications@github.com> wrote:  
 
 


Is your feature request related to a problem? Please describe.
Not really related to a problem , but more for Troubleshooting

Describe the solution you'd like
As a user I would like too see the number of sync packets that Pixelstick is getting just like E1.31 data

Additional context
Add any other context or screenshots about the feature request here.

**Comment by forkineye** [comment]
Would be nice to have the address of the FPP Master that's sending the data.  Not sure if we want to start tracking frame counts or not, but something to actively let the user know that it's receiving data would be nice.   I was planning to change this section anyways to only show status for the active input mode.

**Comment by MartinMueller2003** [comment]
I did make the changes to show only the active stats.

**Comment by patdelaney** [comment]
This has been completed and tested
