### ISSUE TITLE
Add file size and Time stamp to File Management  page output

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#269]
**Is your feature request related to a problem? Please describe.**
As a user I would like to know that date stamp and the file size of sequence files on my pixelstick

**Describe the solution you'd like**
Please add time stamp and file size to the output of the file management page

**Additional context**
![image](https://user-images.githubusercontent.com/8147459/103227535-2d0d5280-48f4-11eb-9ecd-893a57e735d1.png)

**Comment by MartinMueller2003** [comment]
There is a minor problem here. The ESP does not know what time it is so it cannot have meaningful time stamps on the files. Size is no problem. Have to look into the file transfer to see if we can add a time marker to set the ESP local time at the moment the file is transfered. That will not be trivial (aka time zone support would need to be added as well).
Martin
    On Monday, December 28, 2020, 11:05:32 AM EST, patdelaney <notifications@github.com> wrote:  
 
 


Is your feature request related to a problem? Please describe.
As a user I would like to know that date stamp and the file size of sequence files on my pixelstick

Describe the solution you'd like
Please add time stamp and file size to the output of the file management page

Additional context

**Comment by MartinMueller2003** [comment]
At the moment the timestamp uses whatever time is in the browser client. This is the only time source available to the ESP. Size was easy to get. Had to replace the entire display mechanism since it did not support displaying file attributes.

**Comment by patdelaney** [comment]
Just tested time stamp an it appears wrong?
![image](https://user-images.githubusercontent.com/8147459/103351004-6b774e80-4a67-11eb-93f2-d400dcdef9c4.png)

**Comment by MartinMueller2003** [comment]
any file downloaded prior to my latest code changes has a random small time value. delate the file and download it again to get a new date.
martin

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 30, 2020 at 7:23, patdelaney<notifications@github.com> wrote:   


Just tested time stamp an it appears wrong?

**Comment by patdelaney** [comment]
Tested on ESP32 - OK
Tested Wemos D1 - OK

Closing
