### ISSUE TITLE
Web Socket is broken using most recent ESPAsyncWebServer

### ISSUE THREAD

**Issue by sbernath** [forkineye/ESPixelStick#27]
When loading the web site for configuration, I was presented with a message indicating a Web Socket failure. Upon further inspection, socket server was returning a 500 error.

I was able to get the Websocket to function again by using the older version of ESPAsyncWebServer from 11/21/16.

**Comment by forkineye** [comment]
What browser were you using? There's an issue with IE / Edge due to the order the headers come in. I have fix in my fork of it here - https://github.com/forkineye/ESPAsyncWebServer

**Comment by sbernath** [comment]
I tried in Chrome and Safari (Both on Mac) without any luck.  I'll take a look at it this evening and see if that fixed it.
