### ISSUE TITLE
download not working flies seem to be in wrong places

### ISSUE THREAD

**Issue by TheButcherChef** [forkineye/ESPixelStick#275]
--------- Instructions - Delete this ---------
Please provide answers directly below each section.
--------- Instructions - Delete to here ---------
**ESPixelStick Firmware Version**

**Hardware Version**

**Binary release or compiled yourself?**

**Operating System**

**Access Point**

**Describe the bug**

**Comment by TheButcherChef** [comment]
Espflash tool seems to be in wrong folder??

**Comment by forkineye** [comment]
Closing due to no information
