### ISSUE TITLE
V2.0 problem storing settings in web browser.

### ISSUE THREAD

**Issue by comicrcc** [forkineye/ESPixelStick#28]
I loaded the newest version on my 3 Pixelsticks from renard.  Works great.  Loaded it on the renard ESP module and it works.  Tried to go into serial settings and it say DMX not Renard.  Tried to change and save but goes back to old settings.  Most of the fields will not stay.  Is this a problem????

**Comment by forkineye** [comment]
I can't recall hearing any other reports of this.  I ran both DMX and Renard this past season and didn't experience it either. You ever get it worked out?
