### ISSUE TITLE
Unify: Brightness selector shows a warning if I select .05 for brightness

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#296]
**ESPixelStick Firmware Version**
Jan 27 2021 - 10:43:05

**Hardware Version**
Wemos D1

**Binary release or compiled yourself?**
not sure

**Describe the bug**
The web ui in Unify branch show a warning if I change the brightness to .05. I can save the value and it does lower the brightness. For testing I don't need the pixels to be full on, I'm ok with a value of .05 just don't flag it as an error in the UI.

![image](https://user-images.githubusercontent.com/8147459/107045208-df092b80-678a-11eb-817a-240123b3fcf7.png)

**Comment by MartinMueller2003** [comment]
The minimum value is 0.1. That means your 0.05 value is too small.
                <input type="number" class="form-control is-valid" id="brightness" step="0.01" min="0.1" max="1.0" value="1.0" title="Maximum brightness is 1.0." onchange="refreshPixel()">

Do we want to change the definition?
Martin
    On Friday, February 5, 2021, 09:19:51 AM EST, patdelaney <notifications@github.com> wrote:  
 
 


ESPixelStick Firmware Version
Jan 27 2021 - 10:43:05

Hardware Version
Wemos D1

Binary release or compiled yourself?
not sure

Describe the bug
The web ui in Unify branch show a warning if I change the brightness to .05. I can save the value and it does lower the brightness. For testing I don't need the pixels to be full on, I'm ok with a value of .05 just don't flag it as an error in the UI.

**Comment by patdelaney** [comment]
But .05 does lower the actual output whether the UI likes it or not :-)

**Comment by forkineye** [comment]
We need to change this to a percentage (1-100%) instead of the decimal value that I originally coded it as.  Have had a few users confused about it.

**Comment by MartinMueller2003** [comment]
ok I will change it.
Martin
    On Friday, February 5, 2021, 10:23:18 AM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 


We need to change this to a percentage (1-100%) instead of the decimal value that I originally coded it as. Have had a few users confused about it.

**Comment by MartinMueller2003** [comment]
Pull request created.

Martin
    On Friday, February 5, 2021, 11:05:04 AM EST, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  ok I will change it.
Martin
    On Friday, February 5, 2021, 10:23:18 AM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 


We need to change this to a percentage (1-100%) instead of the decimal value that I originally coded it as. Have had a few users confused about it.

**Comment by MartinMueller2003** [comment]
This has been changed to a value 1 - 100 and has been integrated into the Unify branch.

**Comment by patdelaney** [comment]
Even though the UI was switch to be 1-100%   I can still put in .5
and click save it
![image](https://user-images.githubusercontent.com/8147459/107289150-31b44300-6a2a-11eb-89fe-0a73ee9de02a.png)

**Comment by MartinMueller2003** [comment]
Added code to disable the save button when a field has an invalid value.

**Comment by patdelaney** [comment]
Fixed
