### ISSUE TITLE
Enhancement: Support local ISP email servers not just gmail

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#301]
**Is your feature request related to a problem? Please describe.**
We need to update FPP to support more that just gmail as an email relay. We should be able to support local ISPs

**Describe the solution you'd like**
Add other email relay options to FPP 5.0

**Additional context**
This is a place holder for research

we are currently using exim4 under the hood

**Comment by MartinMueller2003** [comment]
did you mean to put this in an fpp thread?
martin

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 15, 2021 at 18:54, patdelaney<notifications@github.com> wrote:   


Is your feature request related to a problem? Please describe.
We need to update FPP to support more that just gmail as an email relay. We should be able to support local ISPs

Describe the solution you'd like
Add other email relay options to FPP 5.0

Additional context
This is a place holder for research

we are currently using exim4 under the hood

**Comment by patdelaney** [comment]
Oops   yes it was supposed to go in FPP
