### ISSUE TITLE
Option in web interface to change Sacn port number

### ISSUE THREAD

**Issue by CTI-Tim** [forkineye/ESPixelStick#320]
Some installs need a custom port number for sacn.  can we get an option to set a custom port number?

**Comment by MartinMueller2003** [comment]
This is easy enough to add in the pixelstick code, but the E1.31 library we use does not support setting the E1.31 port for unicast PDUs. Shelby would have to take a look to see how difficult this would be.
Martin
    On Wednesday, May 12, 2021, 09:09:58 AM EDT, CTI-TimGray ***@***.***> wrote:  
 
 


Some installs need a custom port number for sacn. can we get an option to set a custom port number?

**Comment by MartinMueller2003** [comment]
Added this as an option displayed when in "advanced" mode. A Reboot will happen when this value is changed.
