### ISSUE TITLE
Missing CSS file 

### ISSUE THREAD

**Issue by nyckidryan** [forkineye/ESPixelStick#327]
**ESPixelStick Firmware Version**
4.0 dev unity fork (need support for RGBW)

**Hardware Version**
3.0

**Binary release or compiled yourself?**
Compiled from repository

**Operating System**
Windows 10

**Access Point**
Netgear Orbi

**Describe the bug**
Unable to configure using web UI, possibly due to mising linked stylesheet esps.css in index.html.

[screenshot](https://imgur.com/a/lIGFlvU)

**Comment by nyckidryan** [comment]
![UI missing CSS definitions](https://user-images.githubusercontent.com/77482749/124223237-54c2ba80-dad1-11eb-874e-1b07857c05e9.png)

**Comment by MartinMueller2003** [comment]
esps.css is a compiled file created by gulp. This indicates that gulp failed and the files in the ../data/www directory are not complete. Most likely the esps.js file is also missing. If you press F12 and look at the errors on the console tab, you should see a single error indicating favicon could not be loaded (we dont have a favicon but the browser tries to load one by default).

**Comment by MartinMueller2003** [comment]
This is an install issue and is not present any any of my testing
