### ISSUE TITLE
Merge issue in index.html

### ISSUE THREAD

**Issue by DanielNagy** [forkineye/ESPixelStick#337]
Looks like there is an inline merge issue in the index.html file

https://github.com/forkineye/ESPixelStick/blob/c6881d656dc1bf5ec0e38b142d4c88f83186422a/html/index.html#L427

Line L427 to L431 to L442

**Comment by forkineye** [comment]
I'll get that cleaned up today, thanks!

**Comment by MartinMueller2003** [comment]
Fixed. Pull request has been generated.
Martin
    On Wednesday, August 11, 2021, 07:08:41 AM EDT, Shelby Merrick ***@***.***> wrote:  
 
 


I'll get that cleaned up today, thanks!


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by forkineye** [comment]
Thanks @MartinMueller2003, merged.
