### ISSUE TITLE
[4.0.0-beta1] 

### ISSUE THREAD

**Issue by henrygab** [forkineye/ESPixelStick#361]
--------- Instructions - Delete this ---------
Please provide answers directly below each section.
--------- Instructions - Delete to here ---------
**ESPixelStick Firmware Version**
4.0.0-Beta1 (7083637f81f53b5b15c9fefd2b28f192c30334b6)

**Hardware Version**
ESPixelStick v3

**Binary release or compiled yourself?**
Binary release

**Operating System**
N/A

**Access Point**
Ubiquiti Nanostation M2 Loco

**Describe the bug**

### Steps to repro:
1. Load 4.0.0-Beta1 firmware onto new D1 mini
2. goto `Device Setup` tab
3. Change `Primary Input` to `DDP` (leave secondary input disabled)
4. Change `Output 1` to `WS2811`
5. Review HTML elements

### Expected results:

It appears that ESP32-specific HTML elements should have the `esp32` class.  For example, the `div` element wrapping the `cs_pin` input element does not have the `esp32` class.  The `cs_pin` configuration is only valid for SPI (e.g., APA102) output, which is only used on ESP32.

It appears that, without this class applied, javascript cannot determine that this element should be ignored on ESP8266.

![ESPixelStick_4_0_0_Beta_MissingClasses](https://user-images.githubusercontent.com/740168/134826263-b0be4479-422a-47b2-8490-83268e8cb20f.PNG)

**Comment by forkineye** [comment]
Closing in favor of https://github.com/forkineye/ESPixelStick/issues/360 as it's really the same issue.
