### ISSUE TITLE
fppjson.php?command=getSysInfo&simple not returning correct major version

### ISSUE THREAD

**Issue by computergeek1507** [forkineye/ESPixelStick#364]
**ESPixelStick Firmware Version**
FW Version
CI-1279404057

Build Date
Sep 27 2021 - 17:56:28

**Hardware Version**
Lolin D32 Pro

**Binary release or compiled yourself?**
Release Action https://github.com/forkineye/ESPixelStick/actions/runs/1279404057

**Operating System (and version)**
Windows 10 Pro 21H1

**Web Browser (and version)**
Chrome 93.0.4577.82 

**Access Point**
Ubiquiti UAP-AC-LR

**Describe the bug**
the endpoint "/fppjson.php?command=getSysInfo&simple" returns a major version of '0'. xLights FPP Connect is looking for version "4" to upload a sequence.

![image](https://user-images.githubusercontent.com/2293065/135022019-f7410b65-da1e-4d80-bdbe-c7c50568dcda.png)

**Comment by MartinMueller2003** [comment]
Not sure when this changed. Other have been playing in this area. I will take a look.

**Comment by MartinMueller2003** [comment]
Not sure why you are not getting the correct info. This is what I see:

![getStatusInfo](https://user-images.githubusercontent.com/8608503/135076460-d6783eeb-3a5c-437a-9115-d328ce782031.JPG)

**Comment by computergeek1507** [comment]
I thing it's because I flashed the release action, Shelby changed it to be the build number and not have the major version number I think

**Comment by MartinMueller2003** [comment]
That would be a problem. 
Martin
    On Tuesday, September 28, 2021, 07:19:06 AM EDT, Scott H. ***@***.***> wrote:  
 
 


I thing it's because I flashed the release action, Shelby changed it to be the build number and not have the major version number I think

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by forkineye** [comment]
Yeah, there is no major version related to the CI builds. I'll change that today,

**Comment by forkineye** [comment]
Fixed in the following build - https://github.com/forkineye/ESPixelStick/actions/runs/1282596145
Also, I'm going back to x.y versioning instead of x.y.z in the next beta. 

Leaving this open until the next beta others that may experience the same issue.
