### ISSUE TITLE
File Manager Download Button

### ISSUE THREAD

**Issue by computergeek1507** [forkineye/ESPixelStick#369]
Add the ability to download FSEQs off the SD card from the web interface. I'm using FPP Connect to upload FSEQ files and to analyze the files I have to pull the SD card and insert it into my PC.

**Comment by rbearwy** [comment]
Coputergeek1507 I tried to load them that way and still can not see it in the file manager on the ESP Stick.  They are there when I removed the disk and checked on my computer but they are not showing using the IP address for the ESP Stick
