### ISSUE TITLE
[4.0-beta2] Refresh rate does not update when first enabling output

### ISSUE THREAD

**Issue by henrygab** [forkineye/ESPixelStick#371]
This one should be an easier fix.  😀 

--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-beta2

**Hardware Version**
ESPixelStick v3

**Binary release or compiled yourself?**
Binary release

**Operating System (and version)**
Win10 64-bit (21H1 build 19043.1237)

**Web Browser (and version)**
94.0.992.31 (Official build) (64-bit)

**Access Point**
Ubiquiti Loco M2

**Describe the bug**

### Steps to Repro

1. Clean install 4.0-beta2 on ESPixelStick v3 hardware
2. Logon via WiFi
> <details><summary>Expand for screenshot</summary><P/>
>
> ![ESP8266_4 0-beta2_Home](https://user-images.githubusercontent.com/740168/135503288-f678b130-8511-4164-ba1c-982e7b73a1bf.PNG)
> </details>
3. Click on `Device Setup` tab
> <details><summary>Expand for screenshot</summary><P/>
>
> ![ESP8266_4 0-beta2_DeviceTab_Init](https://user-images.githubusercontent.com/740168/135503439-bf19b5ac-8bb1-4aee-9c0a-42bc8d60415a.PNG)
> </details>
4. Set primary input to DDP _[optional step]_
> <details><summary>Expand for screenshot</summary><P/>
>
> ![ESP8266_4 0-beta2_DeviceTab_Init](https://user-images.githubusercontent.com/740168/135503439-bf19b5ac-8bb1-4aee-9c0a-42bc8d60415a.PNG)
> </details>
5. Set output 1 to WS2812
> <details><summary>Expand for screenshot</summary><P/>
>
> ![ESP8266_4 0-beta2_DeviceTab_SetDDP](https://user-images.githubusercontent.com/740168/135505426-4ab4a2e9-e6df-4abf-ba24-bb331151e07d.PNG)
> </details>

### Expected Results:

Refresh rate shown for default WS2812 configuration

### Actual Results:

Refresh rate does not initially appear (shows zero fps)

![ESP8266_4 0-beta2_DeviceTab_SetWS2812](https://user-images.githubusercontent.com/740168/135506452-e8f55f6f-3a0f-4fe8-a9e0-09cbbf8772b0.PNG)

### Other details:

* If you do not save the config, this will reproduce easily by reloading the page.
* After enabling the output type, changing any setting related to `Output 1` will cause the refresh rate to update ... even for unrelated items such as `Gamma Value` or `Brightness`

**Comment by forkineye** [comment]
That one was on mine todo list, was hoping to get to it before someone noticed :)

**Comment by henrygab** [comment]
Amazing quantity of new features.  I'm quite impressed so far.

Low-pri request:  Consider providing ELF binaries / debug files with releases?  
Why: I've hit exceptions running Beta1, but didn't find the necessary files to decode it.
(yes, I will upload the exception next time, regardless)

**Comment by forkineye** [comment]
> Amazing quantity of new features. I'm quite impressed so far.
> 
> Low-pri request: Consider providing ELF binaries / debug files with releases? Why: I've hit exceptions running Beta1, but didn't find the necessary files to decode it. (yes, I will upload the exception next time, regardless)

Thanks! The ELF files are in the Debug Files workflow artifact. For 4.0-beta2, it was this one - https://github.com/forkineye/ESPixelStick/actions/runs/1288169896

**Comment by henrygab** [comment]
> We have been chasing a bug rooted in the asyncwebserver / websocket library that we're using.

Ah.  I was experiencing it when I was debugging the scripts, with breakpoints set in the validation routines. This cause fairly consistent loss of connectivity.   I offer this information as just one data point that may helps focus testing.

<details><summary>Steps (expandable)</summary><P/>

1. in edge, load `device setup` tab
2. enable `dev tools` by pressing F12
3. in dev tools, goto `sources` tab
4. click on `esps.js` file in left side panel
5. click `yes` to pretty-print the file
6. `CTRL-F` to find string `validity` to find function of interest
7. Right-click on line number for that function, choose `Add Breakpoint`
8. change device configuration to cause breakpoint
9. delay random time
10. resume script (I don't know keyboard shortcut... Click on play icon)
11. repeat steps 8-10

</details><HR/>

**Comment by forkineye** [comment]
Fixed in https://github.com/forkineye/ESPixelStick/commit/e1774d04463ac1c35baedec807c2fb27cedca1f5 CI Build:  https://github.com/forkineye/ESPixelStick/actions/runs/1296427939

BTW, if you ever want to play around with editing the web side, you can change the scripts around in index.html and serve the pages with python, passing your device as target for the websocket stuff. Instructions here - https://github.com/forkineye/ESPixelStick/tree/main/html#development

**Comment by henrygab** [comment]
> BTW, if you ever want to play around with editing the web side, you can change the scripts around in index.html and serve the pages with python, passing your device as target for the websocket stuff.

Well, now... that's a nifty feature!  Turns out Windows prevents the use of port 8000.  I've added PR https://github.com/forkineye/ESPixelStick/pull/374 to suggest use of port 8888 instead.

In addition, it appears `index.html` expects `esps.js` and `esps.css` to exist in the same directory.  files in the depot are in a subdirectory, while index.html expects those files to be in the root.  This adds steps to development / testing (and thus a potential place for errors to occur ... tested files not matching checked in files).

Q: Can you help me understand if this is intentional?  Do the development docs need an update?

**Comment by forkineye** [comment]
That's odd that 8000 was blocked for you. I've worked on a few window machines and never experienced it. As for file structure, the js and css files are all processed via gulp to be minified and comments stripped. When setting up a dev environment, you're pointing to the sources.

**Comment by henrygab** [comment]
Tested build 4.0-ci1296427939, and can happily confirm the issue is resolved.  Thanks!

_[[ As for dev:  OK.  I had just some hope that requiring edits, after testing from the dev environment, would be possible.  Sounds like it's not "low-hanging fruit" (easy to accomplish).  Thanks. ]]_

**Comment by forkineye** [comment]
> Tested build 4.0-ci1296427939, and can happily confirm the issue is resolved. Thanks!
> 
> _[[ As for dev: OK. I had just some hope that requiring edits, after testing from the dev environment, would be possible. Sounds like it's not "low-hanging fruit" (easy to accomplish). Thanks. ]]_

Thanks! Yeah, I agree it's painful as we have to edit and restore index.html constantly. Without migrating to a more involved processing system for the web stuff we're stuck with it as is. I'm working on a reactjs replacement which is going to replace all of it anyways so we've just been dealing with for now.

**Comment by henrygab** [comment]
So... for ESP32, with advanced mode enabled on admin tab...

There are no pins listed for output 7 (e.g., APA102) nor for output 8 (neither relay nor servo pca9685).

Is there any reason to not provide similar information on which pins are used for these?  I was going to file a bug, but if there's reason not to indicate which pins are being used for APA102's clock/data lines, or for I2C (for pca/relay), it'll save me filing a useless issue.

**Comment by forkineye** [comment]
Relay has its own configuration page, can't recall the others though. Will have to check tomorrow. I'd open an issue on it or add to the one you have on grouping if somethings not right.

**Comment by MartinMueller2003** [comment]
That is on purpose. Changing the spi pins is very complicated so it is not supported. You cant change the singular SPI pins without a recompile.

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 1, 2021 at 20:07, Shelby ***@***.***> wrote:   


Relay has its own configuration page, can't recall the others though. Will have to check tomorrow. I'd open an issue on it or add to the one you have on grouping if somethings not right.


— the 
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by forkineye** [comment]
Ah, ok. I couldn't recall if the pin mux on the esp32 supported that or not.

**Comment by henrygab** [comment]
> That is on purpose. Changing the spi pins is very complicated so it is not supported. You cant change the singular SPI pins without a recompile.

Hi Martin,

Can you help me understand this more?

I understand that two sets are pre-defined as IOMUX ("direct") pins, theoretically supporting 80MHz.

At the same time, IIRC, any other pins could be used, although that means they'll go through the GPIO matrix, thus limiting SPI to theoretical 40MHz.  Since that's much faster than APA102 communicates at, I didn't think that would matter.

Seems I'm missing parts of this picture... Can you help me understand (or point me to stuff to read) to get me up to speed?  Thanks!
