### ISSUE TITLE
FPP Remote multisync drift

### ISSUE THREAD

**Issue by forkineye** [forkineye/ESPixelStick#380]
**ESPixelStick Firmware Version**
4.0-beta3

Created from issue reported at [doityourselfchristmas.com](http://doityourselfchristmas.com/forums/showthread.php?56915-ESPixelStick-4-0-0-beta1-Release&p=541716#post541716):
>I'm having some sync issues where it seems like the ESP's are running ahead of the master. Looking at the Multisync page in FPP hints that they are drifting fast. ( At the start of the song they are in time.. At 1 minute they are ahead by 3 seconds.. Any ideas? I've tried Unicast Sync, Multicast and broadcast but none seem to make a difference. Here is an example of the multisync page:

![image](https://user-images.githubusercontent.com/4047923/136199450-d3680a52-05ca-4aa2-ad1e-66a4dd71672f.png)

**Comment by MartinMueller2003** [comment]
Also, even if the FPP and ESP are in synch, the ESP can be off time by an almost fixed amount. There is an adjustment on the device screen that lets you make the ESP lead or lag the FPP by a fixed number of milliseconds.

**Comment by forkineye** [comment]
@MartinMueller2003  Good to close this now?
