### ISSUE TITLE
xLights configuration definition for ESP32 needs updated

### ISSUE THREAD

**Issue by brmeadows2841** [forkineye/ESPixelStick#384]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
ESPixelStick-4.0-beta3

**Hardware Version**
ESP32 D1 Mini

**Binary release or compiled yourself?**
self compiled

**Operating System (and version)**
Windows 11 21H2 - 22000.194

**Web Browser (and version)**
Version 94.0.4606.71 (Official Build) (64-bit) 

**Access Point**
Asus ac5300 - 10.0.0.1

**Describe the bug**
While the esp32 is set for 6 outputs - WS2811
Xlights's visualizer only show 2 pixel ports - port 1 port 2 and serial port 1
I have the ESPixel firmware configured for 100 leds on each output - the Vixualizer in Xlights shows 0 pixels and has only 2 pixel port and 1 serial port.

![image](https://user-images.githubusercontent.com/81775646/136717300-13cbffeb-f3aa-4f17-ae7a-d12ad10cc866.png)

**Comment by forkineye** [comment]
The controller definition in xLights needs to be updated for ESP32 platforms.  For now, you'll need to do ESP32 configuration manually.

**Comment by brmeadows2841** [comment]
Thank you, I have changed the definition in xlights.
