### ISSUE TITLE
Add Scheduling for FPP Remote -> FSEQ File To Play

### ISSUE THREAD

**Issue by onewithhammer** [forkineye/ESPixelStick#385]
I would like to see scheduling option for FPP Remore -> FSYS File to Play.

Even something very simple such as start and stop times on which days?

I understand there isn't a real time clock but perhaps NTP to set the time?

**Comment by forkineye** [comment]
The issue with adding NTP is that we're constrained on the number of ports / sockets we can have active.  This can be done with MQTT though if you have home automation in place.

**Comment by onewithhammer** [comment]
Thank you
