### ISSUE TITLE
When configuring from xlights leave input to fpp remote if previously selected. 

### ISSUE THREAD

**Issue by bloojoop** [forkineye/ESPixelStick#388]
**Is your feature request related to a problem? Please describe.**
I have my pixlestick configured as fpp remote. works great.  If I use xlights visualizer and assign a prop, then upload outputs to configure the output settings it also changes the input to be the configured protocol (ddp in my case).  I do have the inputs and output linked in xlights preferences for my other controllers.  is there a way to leave it on fpp remote when uploading if that is what was set pre upload ? 

**Describe the solution you'd like**
If selected to fpp remote, leave it on fpp remote when uploading from xlights. 

**Additional context**
4.0 beta 3 and espixlestick v3 hardware.

**Comment by MartinMueller2003** [comment]
In my opinion, this is an xLights bug. However, Shelby has a good idea for an enhancement that can get us part of the way. I am going to split the FSEQ support into two parts: 

1) Local File PLay gets moved to the secondary input mode of operation.
2) Primary FPP Remote stays where it is but local file play gets removed.

Currently there is nothing stopping xLights from uploading files at any time. I suggest we tell the xLights team to add FPP Remote to the list of available input modes. Actually, they should get the list from the input_config file and present the choice list found in the config.
