### ISSUE TITLE
Controller Name Issue with Discover controller option

### ISSUE THREAD

**Issue by onewithhammer** [forkineye/ESPixelStick#398]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
ESPixelStick 4.0-beta3

**Hardware Version**
V3

**Binary release or compiled yourself?**
Binary Release

**Describe the bug**

In xLights when using the Discover controller option, the controller name uses the default name not the host name.

I have included 3 screen shots.  One with the default name "DDP_192_168_0_27". One with the correct name "ESPixelStick-V4-3-DMX" and the device configuration screen.

Sometimes it will retrieve the correct name and other times it uses the default name.

<img width="1507" alt="Correct-Name" src="https://user-images.githubusercontent.com/10877476/138740829-43f71116-f92f-4f4d-9f4f-4e684289236c.png">
<img width="1507" alt="Default-Name" src="https://user-images.githubusercontent.com/10877476/138740831-fd239c83-8962-4ac9-88a9-49e8308378c2.png">
<img width="1508" alt="Config" src="https://user-images.githubusercontent.com/10877476/138740832-542d0087-7101-455e-ba86-82d4f8e11cb7.png">

**Comment by thomastech** [comment]
I'm experiencing this problem too. Being a new user I wasn't sure what was going on. Thanks to this reported issue ticket I now understand why it occurs.

I'll hang tight and wait for the fix. Which I understand would involve the xLights app, not ESPixel.

- Thomas
