### ISSUE TITLE
Cannot connect to WiFi AP with complex password

### ISSUE THREAD

**Issue by darranwil** [forkineye/ESPixelStick#404]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

ESPixelStick 4.0-beta3, 2, & 1

Aideepen D1 PRO Development Board ESP8266 CP2104 16M Bytes External Antenna (Wemos D1 mini clone)
EP32-CAM
Wemos D1 Mini

(tested on all 3)

Tested with both precompiled binary and compiled myself.

Win10 64bit

Firefox 93

Luxul 1510 and 1440 access points, Tenda N301 access point

First tested with v3.2 and had no issues connecting to luxul access points except in one location with high amount of 2.4 RF (like 40 of them, for realz).  Luxul APs had already been moved to clear channels to fix previous network RF issues.  Clear channel above and below luxul AP's channel.  

Also replaced original wemos D1 mini with Aideepen D1 PRO Development Board and upgraded to the v4.0 Beta 1 firmware.  Could not connect to AP.  

The luxul APs have 4 different SSIDs all with simular passwords and seperate VLans on each. 
 After several days of testing I found I could connect to 1 of the SSIDs but not the others.  Confirmed encryption settings for all SSIDs. All 4 exactly the same. Only difference being the SSID name and password.

Upgraded to Beta 2, then beta 3.
Swapped out D1 Pro with wemos D1 mini, then second D1 Pro. (after long night of diagnosing, reflashing, checking connections, grabbed wrong cord and plugged 12V in, Poof magic smoke from everything)

Replaced D1 Pro with ESP32-Cam. Same result.
Swapped back to D1 Pro. Same result.

Have tried multiple flashes with the precompiled, compiling through VSCode. Still could not connect to desired SSID.

Recreated 2 of the 4 WiFi networks with a Tenda N301 AP.  Still could not connect. Entire journey it's connected to my main home WiFi AP with no issues except the current random rebooting bug.

SO, ok, at this point I'm assuming the Luxul APs aren't the issue.
Changed the complex password to a simple one on the Tenda. Instant connection. Not sure what in the complex password but I'm assuming it is the symbols (!@) even though the others it will connect to have them in the password as well.

Working passwords ( letters & numbers changed, symbols & capiltalization the same):
btwuyvqpacx518!@#
F33q@uy!Ed3j

Refuses to connect:
F33q@uy!Gw0

The 2 that will connect do have SSIDs that are very different from the passwords while the one that won't is very simular in SSID name and password, password is the SSID in Leet Speak (yeah yeah I know).

Just got this far so will reply tomorrow while testing with luxul APs.

A very big thank you to all the developers. Double thank you for adding ESP32-cam support.

**Comment by darranwil** [comment]
Have not tried compiling it in yet.  Have been entering it through the flash util and through the UI.  Just tried it on the luxul access points and still had issues until I set the APs to mixed WPA/WPA2 mode. Which was odd cause on the Tenda AP with it set to WPA2 worked fine.

**Comment by MartinMueller2003** [comment]
Sorry for the delay. 

So I am to understand that when you enter the complex password via the UI (not the flash utility) on one AP the ESP connects and on another AP the ESP using the same complex password does not connect.

To me the fact that one AP connects and another does not indicates the issue is most likely with the AP and that the ESP is handling the special characters properly.
