### ISSUE TITLE
Invert R,G,B output when selecting Relay as rgb control

### ISSUE THREAD

**Issue by 9ghost9** [forkineye/ESPixelStick#434]
As the title requests ,In testing 0 = 255 brightness  and  128 = 0 
This does not work well for sequencing .

Now that I have played with the settings and have a better understanding of the relay function .
This firmware is awesome .

Thank you

**Comment by MartinMueller2003** [comment]
I have found a bug (aka missing statement) in the PWM processing path that ignored the invert option. This will be fixed shortly. I am also going to add a frequency selector to allow adjustments to the base PWM frequency on ESP32 devices (cant do it on 8266).

**Comment by MartinMueller2003** [comment]
FYI: The ESP32 PWM frequency defaults to 12000 on this and the older ESP32 builds.

**Comment by 9ghost9** [comment]
You have been relentless in solving issues here Martin . Perfecting this firmware for the Esp32 is greatly appreciated .
It seems to me that 5Khz was a typical user setting for pwm channels and the Esp32 which is fine for rgb but compared to the 8266 @ 1k I believe the 5k still has issue with the optocoupler . I would have to retest a sketch to verify .

As far as pwm on the 8266 and your code , it needs no attention other than inverted output . 

Thanks again for all your great work with this  Martin.
