### ISSUE TITLE
Some ESP-01 boards in the wild only support DOUT Flash mode

### ISSUE THREAD

**Issue by madsci1016** [forkineye/ESPixelStick#44]
Well, here's the result of hours lost today. Bought some ESP-01 from Amazon : https://www.amazon.com/gp/product/B01EA3UJJ4/ref=oh_aui_detailpage_o02_s01?ie=UTF8&psc=1 

And they would not boot after getting flashed by Arduino. Even 'Blink' doesn't work. 

After troubleshooting and pulling hair out, seems the flash chip only supports DOUT mode. Google reveals more people running into the problem. So if we release binaries for future releases, we may have to have an option to let the user select flash mode and just instruct them to cycle it till one works for them.

**Comment by forkineye** [comment]
Too many unknowns to support binaries for all the various 3rd party module, flash configuration, and mappings (like the PUYA chip issues).
