### ISSUE TITLE
I Successfully flashed V4 on an ESP-01

### ISSUE THREAD

**Issue by thecrazy** [forkineye/ESPixelStick#443]
I got my hands on a bunch of Esp-01s' with 4mb of flash, so I thought I'd try to flash V4 on them. Unfortunately, the V4 flash tool is giving me errors, I initially thought it was the baud rate / connection settings, so I tried:
`bin/win32/python3/python bin/upload.py --chip auto --baud 115200 --port COM3 --before default_reset --after hard_reset write_flash 0x0 firmware/esp8266/d1_mini-app.bin 0x200000 firmware/filesystem.bin`
but it still didn't work, so I tried the other firmware esp8266/espsv3-app.bin, still a no-go.

Any idea why it's not taking the flash? I know you said the 1 MB version was no longer supported, but now that they have 4 MB shouldn't it work?

**Comment by thecrazy** [comment]
I found a data sheet for the flash chip: https://datasheet.lcsc.com/lcsc/1811072025_XMC-XM25QH32BHIG_C328460.pdf

**Comment by thecrazy** [comment]
Ok I managed to flash V4 on the ESP-01s. To be able to do so I had to put the V4 firmware files in the V3 flash tool and added matching entries for it in the json files. I also had to replace mkspiffs with mklittlefs (just renamed it to mkspiffs cause it seemed harccoded?) thankfully they have the same parameters.

The only problem i'm having (and its the same problem on a nodemcu I tried V4 on before) the effects testing output is completely messed up. Most of the effects are messed up (except rainbow somehow) but the tests in xlights work. Also, I had to manually change the gamma setting which is not a big deal but its the first time I had to do it. It was at 1 instead of 2. Maybe I changed it by accident.

Now if someone could tell me how to keep gpio2 high at boot, that would be great!

**Comment by forkineye** [comment]
You should be able to use the V4 flashtool. You can edit the baudrate in the firmware.json file.  I think you're talking about GPIO0? Pull it to 3.3v through a 10k resistor.

**Comment by MartinMueller2003** [comment]
Not sure why you are having issues with the effects. They dont really know what hardware you are on. All they are told is how many channels are being used.

**Comment by thecrazy** [comment]
It's not the baud rate, It works fine with V4's default speed using the V3 flash tool. I'll run more tests tomorrow, but V4 definitely has communication issues with the esp-01. I don't think the problem is with my computer, I flashed it on many NodeMCU and never had an error.

While googling around, I read something about one of the tools in the bin folder having communication difficulties with the esp at some point. Didn't check the versions, so I'm not 100% sure.

Did any of the toll/library change going from V3 to V4?

**Comment by thecrazy** [comment]
@MartinMueller2003 @forkineye Whats the difference between selecting Espixelstick V3 and Wemos mini D1 in the flash tool? Which one should we be using for a stand alone esp8266?

**Comment by forkineye** [comment]
The Generic Wemos version adds a secondary output for relays and pwm.  The V3 binary doesn't include it since it's a DIY thing and not physically supported on the V3 hardware. If rolling your own, I'd use the generic wemos version.
