### ISSUE TITLE
Unable to update firmware from web interface on 4.0-Beta3

### ISSUE THREAD

**Issue by jeffu231** [forkineye/ESPixelStick#446]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-Beta3

**Hardware Version**
V3 Wemos

**Binary release or compiled yourself?**
Beta release from Github

**Operating System (and version)**
Mac OS

**Web Browser (and version)**
Safari 15.1

**Access Point**
Microtik

**Describe the bug**
I downloaded the 4.0-Beta 4 and used the tool to generate the EFU files to upload. I uploaded to 4.0-Beta3 and it uploads and appears to flash. Upon reboot version is unchanged. Device was deployed and I did not want to bring it in to physically flash it.

**Comment by DrAnonymous** [comment]
I tried the same thing using my D1 mini and it didn't work. Looking at the serial output, the ESP threw an exception shortly after it started the update and rebooted. I was using OSX Catalina and Chrome.

**Comment by forkineye** [comment]
The 4.0 betas don't support EFU updates yet.

**Comment by DrAnonymous** [comment]
Should this be left open until that feature is implemented? Is there a feature list for v4 beyond this?

**Comment by forkineye** [comment]
There was a note about it in the original 4.0 beta. I'll leave this open until it's implemented.

**Comment by MartinMueller2003** [comment]
Changes are in main
