### ISSUE TITLE
Feature request - Status screen when playing seq directly from Xlights - DDP source

### ISSUE THREAD

**Issue by brmeadows2841** [forkineye/ESPixelStick#474]
**Is your feature request related to a problem? Please describe.**

It would be good if when playing a seq directly from Xlights if on the home/status page the name of the seq or some indication of what is being displayed.

**Describe the solution you'd like**

It would be good if when playing a seq directly from Xlights if on the home/status page the name of the seq or some indication of what is being displayed.
![ESpixelstick screen shot of status screen](https://user-images.githubusercontent.com/81775646/154551502-c757109d-32d8-49c0-98a8-4f8508ba1f92.png)

**Additional context**

**Comment by MartinMueller2003** [comment]
The problem is that the name of the sequence is not in the DDP data stream. If xLights were to add that and let us know the protocol for extracting the info, I would be happy to add this.

**Comment by brmeadows2841** [comment]
Im guessing this is not doable as part of the DDP protocol.
I got this from Keith Wesley of Xlights.

[keithsw1111](https://github.com/keithsw1111) commented [yesterday](https://github.com/smeighan/xLights/issues/3134#issuecomment-1049712106)

In DDP it is not possible … there is no place in the protocol to include it. E131 does have a spot to say where data is coming from (64 chars from memory) but right now we just send xLights. We don’t send the sequence name.
