### ISSUE TITLE
Separate structures from global variables in espixelstick.h ?

### ISSUE THREAD

**Issue by penfold42** [forkineye/ESPixelStick#50]
Can I ?

I need the structure definitions in some other work I'm doing and this would make it easier

**Comment by forkineye** [comment]
Are the variables within ESPixelStick.h causing issues with the other code you're working on?

**Comment by penfold42** [comment]
The biggest problem is needing access to the structure definitions from code I want to keep in separate files and/or you might not want in upstream.


Right now the main header file has both globals and all the structure and enum definitions in it so I can't #include it.

**Comment by forkineye** [comment]
It's cleaned up now - https://github.com/forkineye/ESPixelStick/commit/b72296e1ddb6d5383eab529d6bfe3598ec48d033

**Comment by penfold42** [comment]
Thanks !
