### ISSUE TITLE
FPP Remote Drift

### ISSUE THREAD

**Issue by sinh2000** [forkineye/ESPixelStick#530]
Thanks for all your great work!  I have firmware 4.0 beta 4 installed.  I am using a Raspberry Pi 4 as an FPP Player and have the ESPixelStick set as FPP Remote.  I have a 60-second sequence that I am playing in repeat mode.  At the beginning of the sequence each time, it is in sync.  It gradually gets worse and worse until by the end of the minute it's out of sync by a third to a half a second roughly.  I have recreated the sequence to make sure there wasn't something wrong with it.  Any ideas?  Thanks!

**Comment by MartinMueller2003** [comment]
Try ome of the newer builds. a lot of chamges have been made since beta4

**Comment by sinh2000** [comment]
Thanks!  I tried the latest build and it's working much better.  Appreciate it!
