### ISSUE TITLE
I have flood lights that are wrgb which is not in the selection

### ISSUE THREAD

**Issue by stonecreek2007** [forkineye/ESPixelStick#546]
I just purchased new flood lights and they are wrgb which is not a selection  in drop down for color order

**Comment by MartinMueller2003** [comment]
Are they pixels or DMX? What does the rest of the configuration look like?

If they are pixels I can add support to the pixel driver. If they are DMX or Renard or PWM channels then you need to set them up in the sequencer properly. The ESP is blind to those things.

**Comment by MartinMueller2003** [comment]
And looking at the code WRGB is supported for pixels but it was never added to the menus. I have pushed a set of changes to add it to the pixel menu options.

**Comment by MartinMueller2003** [comment]
Changes are in main
