### ISSUE TITLE
Can't change SSID and Password from Web UI

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#55]
I am on the new v3.0 beta. I upgraded from 2.0 with no problems. I am new to Pixelstick. I tried to switch the SSID and password from the Web UI, but it will not allow me to save it. Is that a bug or as designed?

**Comment by penfold42** [comment]
A bit of both - if you edit the host name it triggers a field validation that enables the save button

**Comment by forkineye** [comment]
@patdelaney By not allowed to save, do you mean the button being disabled?  The page now does hostname validation, so if you have a hostname with invalid characters the save button will be disabled.

**Comment by penfold42** [comment]
There's a bug here - the button is disabled by default even if a valid host name is already present.

If I just want to change the SSID, I still need to make a tiny edit to the host name to enable the button

**Comment by forkineye** [comment]
@penfold42 Ah, thanks!  I'll fix it next time I get a chance to work on the code

**Comment by penfold42** [comment]
I can probably do it - I'll add validation for ssid and key too

**Comment by penfold42** [comment]
I can confirm #58 fixes this

**Comment by forkineye** [comment]
@penfold42  Thanks! I'll merge the PR's this weekend if not sooner.
