### ISSUE TITLE
Error compiling SOURCE

### ISSUE THREAD

**Issue by chassy33** [forkineye/ESPixelStick#555]
I am attempting to compile and build from source but I keep getting an error that just says `Error:`. The error occurs when attempting to install espressif/toolchain-xtensa-esp32. I am new to building from source, but I am just getting no verbose errors to show me what is going on. I followed the instructions in the readme but can't seem to get anywhere. 

![image](https://user-images.githubusercontent.com/28711313/187544983-870a1bfe-7361-4808-b7d8-a7654b2d1179.png)

**Comment by MartinMueller2003** [comment]
That is a problem within platformio. I'll take a look but you would be best served by asking in a platformio forum. There may simply be a setting in PIO that did not get set up on your computer.
Martin
    On Tuesday, August 30, 2022 at 05:18:42 PM EDT, Chace Ausherman ***@***.***> wrote:  
 
 


I am attempting to compile and build from source but I keep getting an error that just says Error:. The error occurs when attempting to install espressif/toolchain-xtensa-esp32. I am new to building from source, but I am just getting no verbose errors to show me what is going on. I followed the instructions in the readme but can't seem to get anywhere.

**Comment by MartinMueller2003** [comment]
I think I may have tracked this down. There is an incompatibility in the WebServer library and the new ESPIDF. I got a similar error after deleting the .pio directory and forcing a complete new build. Please download the latest code, delete the .pio directory (If it is present) and do a build.

**Comment by chassy33** [comment]
Martin,

Thank you for the quick replies! I have not had a chance to do any more testing. I did ask some questions in a platformIO group but got no real answers.  I will give that a try though and let you know.

**Comment by MartinMueller2003** [comment]
Have you verified the fix? I would like to close this.

**Comment by MartinMueller2003** [comment]
Still not seeing any more build errors
