### ISSUE TITLE
Random light data if dmx data < configured led count

### ISSUE THREAD

**Issue by penfold42** [forkineye/ESPixelStick#56]
Should we ensure any missing data is set to black ?

**Comment by forkineye** [comment]
Had intentions to test this past weekend but didn't get to it.  The ring buffers are zero'd out in the E131 library when initialized.

**Comment by penfold42** [comment]
I think the issue is on the espixel stick side when it copies the packet data from the e131 library

**Comment by forkineye** [comment]
Fixed in https://github.com/forkineye/ESPixelStick/commit/8694d2192632d28a13c1a7f8072aab83f57f8bdd
