### ISSUE TITLE
dig-octa does not appear for flash in ESPSFlashTool.jar drop down - build ESPixelStick_Firmware-4.0-ci3315755181

### ISSUE THREAD

**Issue by mstang1988** [forkineye/ESPixelStick#588]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
ESPixelStick_Firmware-4.0-ci3315755181

**Hardware Version**
dig-octa

**Binary release or compiled yourself?**
No

**Operating System (and version)**
OSX Monterey 12.6

**Web Browser (and version)**
Chrome

**Access Point**
Unifi AC-Pro

**Describe the bug**
dig-octa does not appear for flash in ESPSFlashTool.jar drop down to flash so I can only flash the dig quad version of the firmware without walking through the install via command line.

**Comment by MartinMueller2003** [comment]
Are you sure you have the latest version of the flash tool? It is present on the latest.

![image](https://user-images.githubusercontent.com/8608503/203408019-5410a37d-462b-4d56-8f4c-9be1d58b375c.png)

**Comment by mstang1988** [comment]
I used the version that is embedded with the latest CI build available (version published).  I just hacked the json to add it myself and uploaded the firmware.  Let me see if I can download the latest async to the build and if that works.

**Comment by mstang1988** [comment]
It looks like main utilizes a version that is 14 months old and was last updated for dig-quad.

https://github.com/forkineye/ESPixelStick/tree/main/dist

https://github.com/forkineye/ESPixelStick/blob/main/dist/ESPSFlashTool.jar

And the definition file as well:
https://github.com/forkineye/ESPixelStick/tree/main/dist/firmware
https://github.com/forkineye/ESPixelStick/blob/main/dist/firmware/firmware.json

**Comment by MartinMueller2003** [comment]
Use the version found here. It is always up-to-date:
https://drive.google.com/file/d/1DG3wz8lbYNc371OIbeOqkzMaY5Zd2SKA/view?usp=sharing

**Comment by MartinMueller2003** [comment]
Can this issue be closed?
