### ISSUE TITLE
Espixelstick v4.x on ESP32 D1 DevKitC v4 hardware

### ISSUE THREAD

**Issue by gatoruss** [forkineye/ESPixelStick#599]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**

I am using the latest version of v4 downloaded on 12/5 from [google share site]([https://drive.google.com/file/d/1DG3...ew?usp=sharing](https://drive.google.com/file/d/1DG3wz8lbYNc371OIbeOqkzMaY5Zd2SKA/view?usp=sharing))

**Hardware Version**

[MELIFE ESP32-DevKitC (ESP32-WROOM-32U)](https://www.amazon.com/dp/B0811KLGDD?psc=1&ref=ppx_yo2ov_dt_b_product_details)

My device is v4

**Binary release or compiled yourself?**

Binary release ([v3.2](https://github.com/forkineye/ESPixelStick/releases/tag/v3.2))

**Operating System (and version)**

Windows 10

**Web Browser (and version)**

firefox

**Access Point**

**Describe the bug**

I attempted to load the newest version of espixelstick v4 from google share site; however, after installation, when attempting to connect to the network, the serial monitor froze, with the last 3 lines outputted being:

   09:29:16: [WiFiDrv] Using DHCP
  09:29:16: [WiFiDrv] Connecting to 'XmaLitesNet' as espixel01
  09:29:16: E (6944) wifi:Association refused temporarily, comeback time 1048 mSec

[log1205.txt](https://github.com/forkineye/ESPixelStick/files/10156582/log1205.txt)
Log attached. Any help would be appreciated. Is there a more appropriate hardware to select?

In case it means anything, I initially tried to enter a static address in the installer and unchecked is DHCP, with the same result (interesting that the devise used DHCP even when unchecked?).

**Comment by MartinMueller2003** [comment]
09:29:16: E (6944) wifi:Association refused temporarily, comeback time 1048 mSec

This is an issue between the ESP WiFi layer and your AP not releasing resources. You can see a conversation about this here: 
https://github.com/espressif/esp-idf/issues/9428

At any rate, the boot finished properly. not sure why you had trouble accessing the UI. Did the ESP reboot at the time you tried to access the UI?

**Comment by MartinMueller2003** [comment]
I have a devkitC up and running without issues:

[FileMgr] Configuration File: '/config.json' loaded.
[FileMgr] Configuration File: '/input_config.json' loaded.
[FileMgr] Configuration File: '/output_config.json' loaded.
[FileMgr] Configuration File: '/config.json' saved 358 bytes.
[WiFiDrv] WiFi Entering State: Connecting Using Default Credentials
[WiFiDrv] Using DHCP
[WiFiDrv] Connecting to 'MaRtInG' as esps-F01E100EE93C
[WiFiDrv] WiFi Entering State: Connected To AP
[WiFiDrv] Connected with IP: 192.168.10.175
[ WebMgr] Web server listening on port 80
[   FPPD] Listening on port 32320
[ 27802][E][vfs_api.cpp:104] open(): /littlefs/www/index.html does not exist, no permits for creation
[ 28408][E][vfs_api.cpp:104] open(): /littlefs/www/favicon.ico.gz does not exist, no permits for creation
[ WebMgr] WS client connect - 1
[ 36034][E][vfs_api.cpp:104] open(): /littlefs/www/ws2811.html does not exist, no permits for creation
[ 38052][E][vfs_api.cpp:104] open(): /littlefs/www/effects.html does not exist, no permits for creation
[FileMgr] Configuration File: '/config.json' saved 371 bytes.
[FileMgr] Configuration File: '/config.json' loaded.
[FileMgr] Configuration File: '/input_config.json' saved 2945 bytes.
[FileMgr] Configuration File: '/config.json' saved 357 bytes.
[FileMgr] Configuration File: '/input_config.json' loaded.
[InputMgr] Shutting Down 'Disabled' on Input: 1
[InputMgr] Starting Effects Engine for channel '1'.
[FileMgr] Configuration File: '/output_config.json' saved 10388 bytes.
[FileMgr] Configuration File: '/output_config.json' loaded.
[OutputMgr]  Shutting Down 'Disabled' on Output: 0
[OutputMgr] 'WS2811' Initialization for Output: 0
