### ISSUE TITLE
ESPixelStick 4.0-beta4 no file management tab

### ISSUE THREAD

**Issue by Billybojangles01** [forkineye/ESPixelStick#603]
--------- Instructions --------
Please provide answers directly beloESPixelStickw each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-beta4

**Hardware Version**
Dig Octa 

**Binary release or compiled yourself?**
Binary release

**Operating System (and version)**
Windows 10

**Web Browser (and version)**
Any

**Access Point**

**Describe the bug** Trying to send xlights seq to device but since there is no file management tab.  I am not able to save the SD MISO Pin to 36.  Software will not allow me to.

**Comment by MartinMueller2003** [comment]
I just looked at the config and values up to 40 are allowed for MISO. I set it to 35 and then back to 46 and everything on the octa is working as expected. If you are using the octa image from the installer, you should not need to change the GPIO settings.

![image](https://user-images.githubusercontent.com/8608503/206864102-a2c9823b-fd05-4ee1-b95a-daa49fcb6b1f.png)

**Comment by Billybojangles01** [comment]
How can I check my config?  It will not accept anything over 24 for me.

**Comment by MartinMueller2003** [comment]
First, grab the latest dist.zip from my googledrive. That is the exact version I tested. Then post the admin page like you did. I suspect there is something cached on your UI.

**Comment by Billybojangles01** [comment]
> First, grab the latest dist.zip from my googledrive. That is the exact version I tested. Then post the admin page like you did. I suspect there is something cached on your UI.

I can do that.. Where do I find the link to your GoogleDrive?

**Comment by MartinMueller2003** [comment]
https://drive.google.com/file/d/1DG3wz8lbYNc371OIbeOqkzMaY5Zd2SKA/view?usp=sharing
