### ISSUE TITLE
Remove device id ?

### ISSUE THREAD

**Issue by penfold42** [forkineye/ESPixelStick#61]
Does this serve any purpose that hostname can't fulfil ?

**Comment by forkineye** [comment]
The original intent was freeform text to help identify the device when you had many of them.  The same could be done with hostnames now as long as you stick to the naming convention.  However, there are many users out there who have have been using this for a couple of years and utilize the device ID for tracking their controllers who I wouldn't want to inconvenience.  What about some logic to set the Device ID to the hostname if a Device ID doesn't already exist? For example, when flashing utilizing the flash tool.  If they leave it blank there as well, "ESPixelStick" could be used internally for the Device ID until a hostname or Device ID is set by the user.  If Device ID is set, it would take precedence.
