### ISSUE TITLE
Effect - Marquee with Flashes

### ISSUE THREAD

**Issue by MartinMueller2003** [forkineye/ESPixelStick#630]
Please create a new effect that allows the user to simulate a classic Marquee on a string of lights.

This is similar to a chase with two colors and three pixels to a group. The groups move one pixel forward at a time to create the moving chase effect.

There should be a strobe effect that repeats at a given interval over the time the effect is running

The effect is to be started / stopped using an external trigger (aka button)

MEM - The above is from notes taken from an ESP user. The below is an expansion on the feature to make it more generic and useful in a wider setting.

- Groups
    - Allow the user to configure the number of groups to chase
    - Each group can be a different color
    - Each group can be a different size (aka number of pixels in the group)
    - The intensity of the pixels in the group must be able to support a fade in or a fade out effect
- The speed of the chase must be configurable
- Flash:
    - The flash duration must be configurable
    - The flash rate must be configurable
    - Flash rate may be set to "Random". If random then min/max delay times must be set.

The effect will be controlled as the other effects are controlled. There is another ticket open asking to be able to trigger effects using an external trigger. This effect will take advantage of that functionality to meet the button requirement.

**Comment by MartinMueller2003** [comment]
Making progress. Marquee and flashing is working and will be submitted for integration. Triggering is still in progress.

**Comment by MartinMueller2003** [comment]
PR: Added Marquee and Random Flash support. #632

**Comment by PtitBry** [comment]
Hi, Many thanks for your help ;)

**Comment by MartinMueller2003** [comment]
You can give it a try using this image:
https://drive.google.com/file/d/1ihIKCxoccCDYFvfUOL_RCftpTc7yDxYH/view?usp=share_link

**Comment by MartinMueller2003** [comment]
The GPIO used depends on your platform. The pin is configurable as is the polarity and definition of a long pull. 

By default, pulling the assigned pin low for less than 2 seconds is a short push and over 2s is a long push.  You also need to enable the feature via the UI before it does anything.

**Comment by MartinMueller2003** [comment]
Here is a picture of my test setup
![20230524_143648](https://github.com/forkineye/ESPixelStick/assets/8608503/c2bf1db6-4605-4482-93e3-fb3c807fa095)

**Comment by PtitBry** [comment]
I have a "node MCU V3", I think an ESP V3 (ESP 8266MOD).

So I can put the boton on any pin D0 to D8, and the data of the WS2811 strip led ?
Vin : 5Vcc
GND : gnd

**Comment by MartinMueller2003** [comment]
PR Created.

**Comment by MartinMueller2003** [comment]
Integrated into main

**Comment by PtitBry** [comment]
> Integrated into main

Hi, Many Thanks Martin 😁
