### ISSUE TITLE
Cannot flash ESPixelstick V3

### ISSUE THREAD

**Issue by Cassock** [forkineye/ESPixelStick#634]
**ESPixelStick Firmware Version**
3.2

**Hardware Version**
V3

**Binary release or compiled yourself?**
3.2 release from https://github.com/forkineye/ESPixelStick/releases/download/v3.2/ESPixelStick_Firmware-3.2.zip

**Operating System (and version)**
Win11

**Web Browser (and version)**
Chrome 113

**Access Point**

**Describe the bug**
Finally getting around to setting up this ESPixelstick (order 998) with some Costco(?) RGB lights I've had in the garage for a while. When I plug it in via USB, there is no LED indicating it's powered on but Windows donks at me to tell me the device is recognized, and COM3 - USB-SERIAL CH340 (COM3) shows up as an available serial port, but I get this error when attempting to upload. Pressing the reset button does not generate any output.
![image](https://github.com/forkineye/ESPixelStick/assets/15901832/ca50f902-d31c-4abf-9c56-02ad53a86aec)

**Comment by forkineye** [comment]
It's failing to put the module into bootloader mode for some reason (probably a bad module). I contacted you via the email address used on the order and will take care of it. Let me know here if you don't receive anything.
thanks,
-shelby
