### ISSUE TITLE
4.0b5 empty Home screen

### ISSUE THREAD

**Issue by Cassock** [forkineye/ESPixelStick#699]
**ESPixelStick Firmware Version**
4.0 beta 5

**Hardware Version**
Espixelstick V3 from Shelby

**Binary release or compiled yourself?**
Binary release from 3 days ago

**Operating System (and version)**
Win11

**Web Browser (and version)**
Chrome 119 (same in Edge)

**Access Point**
?

**Describe the bug**
Flashed 2 units earlier today and both have an empty Home page as depicted below. Looks like all other functionality is working fine, so just a UI issue along with a bunch of errors in the console. 
![image](https://github.com/forkineye/ESPixelStick/assets/15901832/7de9f7f7-aefd-484c-a83b-e2015c9894f1)
![image](https://github.com/forkineye/ESPixelStick/assets/15901832/53688cf5-9070-4062-8e82-0d50f970a850)

**Comment by fedekrum** [comment]
What I do is to nuke all the ESP8266 data first by uploading an empty script through Arduino IDE.
(There should be more clever ways to do this)
I had problems before reloading ESPixelStick.

**Comment by MartinMueller2003** [comment]
Do the other pages work? Are there error messages coming out on the ESP console?

**Comment by Cassock** [comment]
All other pages work fine. I just reflashed and it appears the Home stats show up fine until I set the secondary input to FPP remote, then get a number of [WebMgr] ERROR: Status Doc is too small. How would you like me to send you logs? I can't attach them here

**Comment by Cassock** [comment]
[120623 logs.txt](https://github.com/forkineye/ESPixelStick/files/13591092/120623.logs.txt)

**Comment by MartinMueller2003** [comment]
This is the critical error:

[WebMgr] ERROR: Status Doc is too small

**Comment by MartinMueller2003** [comment]
Just reproduced this issue.

**Comment by MartinMueller2003** [comment]
Fixed in my latest PR. google drive dist has been updated.
