### ISSUE TITLE
"Page not found"

### ISSUE THREAD

**Issue by ARADDI0929** [forkineye/ESPixelStick#700]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
ESPixelStick-4.0-beta5

**Hardware Version**
ESPixelStick V3

**Binary release or compiled yourself?**

**Operating System (and version)**
macOS Sonoma 14.1.2

**Web Browser (and version)**

**Access Point**

**Describe the bug**
Flashed everything through Visual Studio Code and can't access webpage. When typing in the ip in a browser it says "Page not found". 

Tried flashing in Arduino IDE and the same thing happens.

**Comment by MartinMueller2003** [comment]
I am not seeing this. I am uploading regularly. I suspect you have not uploaded the File System (FS). That would result in such an error.
