### ISSUE TITLE
Store [Diagnostics] tab settings

### ISSUE THREAD

**Issue by fedekrum** [forkineye/ESPixelStick#709]
**Is your feature request related to a problem? Please describe.**
The problem is that each time I access the [Diagnostics] tab after the page reload, "Display As" (RGB, RGBW, Channels) and "Columns" are reset.

**Describe the solution you'd like**
I imagine 2 solutions.
1) Write in the ESP flash these 2 parameters each time a change is made to one of those.
2) Save them on a browser cookie for a long period each time these are changed

**Comment by MartinMueller2003** [comment]
Changes for this are in the latest pull request.

**Comment by fedekrum** [comment]
Which way you went? Cookies or saving values on ESP flash?(or other...)

**Comment by MartinMueller2003** [comment]
cookies. You can test it in my latest dist.zip file.

**Comment by fedekrum** [comment]
Can you post your release's URL?

**Comment by MartinMueller2003** [comment]
https://github.com/MartinMueller2003/ESPixelStick/releases
Use the dist.zip file you find there. The source code is out of date.
