### ISSUE TITLE
OLED Support?

### ISSUE THREAD

**Issue by noman1228** [forkineye/ESPixelStick#728]
I forked and added OLED support (i2c) to show hostname and IP address. It's extremely hacky but doesn't seem to affect performance. It came in handy a few times this season. Nothing exotic, just adafruit library (I know font selection sucks) and a println after network updates... u8g would be even more lightweight.

![20240114_182111](https://github.com/forkineye/ESPixelStick/assets/163939/a4b266ea-a59c-41ac-9310-f21d193d2438)

**Comment by MartinMueller2003** [comment]
Cool. Create a pull request so I can review your code.
