### ISSUE TITLE
MQTT changes need a reboot

### ISSUE THREAD

**Issue by penfold42** [forkineye/ESPixelStick#74]
Or they don't take effect

Perhaps move the config to the Wireless section ?

It's a network thing and there's more screen real estate there than the device tab (especially with my PWM stuff!)

**Comment by penfold42** [comment]
This might not be a bug - I have so many branches, I could have had some unpulled commits.

I still think moving it to network is a good thing.

**Comment by penfold42** [comment]
A robot is triggered if [ ] enabled is changed but not if you change any of the config options.

I am happy to do the work to move this to the wireless settings

**Comment by forkineye** [comment]
MQTT changes trigger a reboot now.
