### ISSUE TITLE
serial port freaks out after specific output config (dig octa)

### ISSUE THREAD

**Issue by marcobrianza** [forkineye/ESPixelStick#751]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-ci8237205806

**Hardware Version**
dig octa

**Binary release or compiled yourself?**
CI. release

**Describe the bug**

after applying this configuration the serial port stats to write strange characters continuously
![screencapture-192-168-11-22-2024-03-11-20_18_14](https://github.com/forkineye/ESPixelStick/assets/1008278/08784768-58c9-4394-98d6-c0a6605985ec)

the last lines of the log before explosion are:

20:18:56.587 -> [FileMgr] Configuration File: '/config.json' loaded.
20:18:56.693 -> [FileMgr] Configuration File: '/input_config.json' loaded.
20:18:57.767 -> [FileMgr] Configuration File: '/output_config.json' loaded.
20:18:57.976 -> ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮

the device looks like it is working anyway

**Comment by MartinMueller2003** [comment]
You configured port 2/3. Those ports use the same outputs used by the USB serial device. You are looking at the pixel data going out.

**Comment by MartinMueller2003** [comment]
That was a Quindor decision. Nothing I could do about it.
