### ISSUE TITLE
esp32_devkitc GPIO settings

### ISSUE THREAD

**Issue by kingofmonkeys** [forkineye/ESPixelStick#752]
I've been trying to get the latest code working on an esp32 devkitc v4 and there appears to be a bug in how the GPIO pins are being defined in the GPIO_Defs.hpp file.  If you look at line 125 there appears to be a copy/paste mistake where its looking for BOARD_ESP32_TWILIGHTLORD_ETH instead of BOARD_ESP32_DEVKITC .  See snippet below. 

#elif defined (BOARD_ESP32_TWILIGHTLORD_ETH)
#   include "platformDefinitions/GPIO_Defs_ESP32_DevkitC.hpp"

**Comment by noman1228** [comment]
I fixed this for that exact dev board. My pull request hasn't been merged yet but my fork will work for you in the meantime. I could also walk you through the lines/files that need to be edited to get you up and running.

**Comment by kingofmonkeys** [comment]
I fixed it for myself, just wanted to get the bug report in so its fixed in the main branch for everyone.

**Comment by MartinMueller2003** [comment]
Fixed in https://github.com/forkineye/ESPixelStick/pull/749
