### ISSUE TITLE
Default Ethernet configuration for Wasatch board with Ethernet is incorrect.

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#766]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-ci9475001076

**Hardware Version**
Wasatch Quad+ 4 onboard ports and  4 Differential Ports

**Binary release or compiled yourself?**
Used Web flasher

**Describe the bug**
When I flashed the firmware (4.0-ci9475001076) I did configure Wi-Fi. After it rebooted and I verified that it would connect. I put the ESP back on the board and connected the ethernet cable, then powered it up. It appears to have reconnected via Wi-Fi and not ETH0.
 
I research the board and the correct settings are below and I tested them with that board.
![image](https://github.com/forkineye/ESPixelStick/assets/8147459/a88867b8-2bee-497a-a631-c952bacfb94f)

**Comment by patdelaney** [comment]
![image](https://github.com/forkineye/ESPixelStick/assets/8147459/56dd9b70-076d-4ec9-8bff-7c4aebbdfe85)

**Comment by MartinMueller2003** [comment]
Corrections for this will be in the next PR.

**Comment by MartinMueller2003** [comment]
This has been merged
