### ISSUE TITLE
Default configuration for LED output GPIO pins (port 8) is incorrect for Wasatch Quad+ board 

### ISSUE THREAD

**Issue by patdelaney** [forkineye/ESPixelStick#767]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-ci9475001076

**Hardware Version**
Wasatch Quad+ 4 onboard ports and 4 Differential Ports

**Binary release or compiled yourself?**
Used web flasher

**Describe the bug**
The version I installed has GPIO3 listed for Output 8. The documentation lists 33.

I changed the GPIO to 33 and lights work as expect.

**Comment by patdelaney** [comment]
![image](https://github.com/forkineye/ESPixelStick/assets/8147459/80f36b40-d9e5-4539-a353-90c335946483)

**Comment by MartinMueller2003** [comment]
A fix for this is available on the web flasher (experimental" version and will be part of the next pull request.

**Comment by MartinMueller2003** [comment]
This has been merged
