### ISSUE TITLE
Using WEB APP >> set as static IP but the programmed IP is different (my first DHCP address in this case)

### ISSUE THREAD

**Issue by iz1kbp** [forkineye/ESPixelStick#774]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
Using the WEB APP and lastest release

**Hardware Version**
WEMOS D1 MINI PRO 16M

**Binary release or compiled yourself?**
DOWNLOAD FROM WEBAPP

**Operating System (and version)**
W11

**Web Browser (and version)**
CHROME LASTEST

**Access Point**
VIA LAN

**Describe the bug**
I tried programming via WEB using last release available. The programming was successful, but although I had programmed a static IP, in the programming log I saw that an IP was set which, in my case, corresponds to the first of the DHCP range
My setup program..
![Cattura](https://github.com/forkineye/ESPixelStick/assets/42711382/431e6c3a-c23b-4855-b3ab-35d5a6c7db98)
log file (2.0.0.100 insted of 2.0.0.28)
![Cattura2](https://github.com/forkineye/ESPixelStick/assets/42711382/5d30586e-430f-443c-92fa-934be1c70d5e)

the release
![Cattura3](https://github.com/forkineye/ESPixelStick/assets/42711382/9683992b-f58b-456b-bf27-b68cd116cce7)

**Comment by MartinMueller2003** [comment]
Found two major issues. Both are fixed.

1. Data was being sent from the UI to the server incorrectly formated/ This resulted in all of the bool settings being corrupted and reverting to factory defaults. 
2. Validation functions could get confused and leave the flash button disabled if a setting is given an invalid value and then cleaned up later.

**Comment by iz1kbp** [comment]
thank you!
:+1:
