### ISSUE TITLE
Home screen shows no data on v4-beta5

### ISSUE THREAD

**Issue by AGFazio** [forkineye/ESPixelStick#776]
**ESPixelStick Firmware Version**
ESPixelStick Firmware v4 - beta5

**Hardware Version**
espsv3

**Binary release or compiled yourself?**
Bianry

**Operating System (and version)**
Windows 11

**Web Browser (and version)**
Edge Version 126.0.2592.113 (Official build) (64-bit)

**Access Point**

**Describe the bug**
When on web home page, pixelstick shows no data. It loads for a short time then when refresh the page it dissapears. 
![espixelstick home page](https://github.com/user-attachments/assets/0532f7ea-573a-482f-81d1-98d1070e2e02)

**Comment by MartinMueller2003** [comment]
Please load the most recent CI build from the Web Flasher. That is a bug that has been fixed.

**Comment by AGFazio** [comment]
Done.  Works.  Thank You.
