### ISSUE TITLE
web installer flooded

### ISSUE THREAD

**Issue by marcobrianza** [forkineye/ESPixelStick#783]
It looks like there is something wrong in the web installer config because the combobox is way longer than needed

![bigcombo](https://github.com/user-attachments/assets/2936c56d-e986-4444-8318-3a2ecbee0871)

**Comment by MartinMueller2003** [comment]
I do not see it from my side. Rebooted the server just in case.

**Comment by marcobrianza** [comment]
it is fixed now

**Comment by marcobrianza** [comment]
well, not really fixed. each time I refresh the page the items a duplicated

**Comment by MartinMueller2003** [comment]
I just hacked in a change to only build the table once. It means I need to reboot every time I add a dist. I will keep looking for a better solution.
