### ISSUE TITLE
Clicking Advanced Mode Has No Effect

### ISSUE THREAD

**Issue by gothambeat** [forkineye/ESPixelStick#784]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-beta3

**Hardware Version**
ESPIXELSTICK V3

**Binary release or compiled yourself?**
Binary Release

**Operating System (and version)**
Windows 11

**Web Browser (and version)**
Google Chrome

**Access Point**
N/A for this issue but UBiquiti managed VLAN network

**Describe the bug**
When selecting the "Advanced Mode" on the administration page,  nothing happens.

**Comment by MartinMueller2003** [comment]
please retry using the latest ci build. i used this yesterday without issue

**Comment by MartinMueller2003** [comment]
Just tested this again and it is working fine. NOTE: When you select advanced mode on the admin page, nothing visible will happen. When you navigate to the device page, you will now see the GPIOs used for the SD card.

**Comment by MartinMueller2003** [comment]
It still works fine for me.
