### ISSUE TITLE
Add TLS 3001 support

### ISSUE THREAD

**Issue by forkineye** [forkineye/ESPixelStick#8]
http://doityourselfchristmas.com/forums/showthread.php?39166-ESPixelStick-E1-31-WiFi-Pixel-Controller&p=413124#post413124

**Comment by forkineye** [comment]
Protocol references:
https://github.com/FastLED/FastLED/issues/1
http://auschristmaslighting.com/forums/index.php?topic=1938.0

**Comment by MartinMueller2003** [comment]
Just looked into this.  The current unify ws2811 output driver with a modified ISR should be able to do this. I would need two or three TLS3001 based pixels to test with.

**Comment by MartinMueller2003** [comment]
These pixels are much more expensive than the WS2811 devices. If you send me a few, I will take a crack at setting up the protocol. Assuming you still want to add this to the Unify branch.

**Comment by forkineye** [comment]
Going to close this out. Don't know of anyone that uses them anymore.
