### ISSUE TITLE
flashing ESP32-generic ends up in device reporting d1_mini32

### ISSUE THREAD

**Issue by dutch-anykey** [forkineye/ESPixelStick#810]
Hi,

I have a ESP32 boards from aliexpress (ESP32-WROOM-32) I flash them as ESP32-generic. (because that's what it basically is imo)

When flashing from the webflasher page, I select "generic ESP32 4MB" Flashing goes well and after reboot when I look at the admin page it says:
FW Version 4.0-ci12244189758
Build Date Dec 9 2024 - 21:01:10
Architecture ESP32
Board Name **d1_mini32** <<not right?
Flash Size4194304
Flash ID84158F0A8AB4

I checked the GPIO DEF files. 
include/platforms/GPIO_Defs_ESP32_generic.hpp inside refers to the  "#include "GPIO_Defs_ESP32_LoLin_D32_PRO.hpp"" file.

But how does it end up becoming a d1_mini32?

**Comment by MartinMueller2003** [comment]
That is correct. The D1-Mini is the basis for the generic build.
