### ISSUE TITLE
Static firmware

### ISSUE THREAD

**Issue by Kamal-Sonani** [forkineye/ESPixelStick#99]
Instead of setting options on web for universe boundary and pixel count , i think flasher should have veriable to set once and program. Like **SSID ,PASSWORD ,HOST ID Etc** 

Flasher feature from my side👇

-  Defult output value is 170 pixels(510 channel)
    Set it to max with 680(2040 ch=4 universe)
-  Ap fallback check box
-  Add Universe boundary and pixel count text box👍 
-  Read and Show Mac address of Espixelstick for
   Set fix ip to module **OR** static ip set with Ip's
   textbox.

**Comment by forkineye** [comment]
The defaults that are flashed when using the flash tool can be changed by editing the config.json file.
